"""Chinese-to-English country name mapping for freight calculator."""

CN_TO_EN: dict[str, str] = {
    # ── East Asia ──
    "中国香港特别行政区": "Hong Kong",
    "中国澳门特别行政区": "Macau",
    "韩国": "South Korea",
    "中国台湾地区": "Taiwan",
    "日本": "Japan",
    "蒙古": "Mongolia",
    # ── Southeast Asia ──
    "文莱": "Brunei",
    "印度尼西亚": "Indonesia",
    "柬埔寨": "Cambodia",
    "老挝": "Laos",
    "马来西亚": "Malaysia",
    "菲律宾": "Philippines",
    "新加坡": "Singapore",
    "泰国": "Thailand",
    "越南": "Vietnam",
    "缅甸": "Myanmar",
    "东帝汶": "Timor-Leste",
    # ── South Asia ──
    "印度": "India",
    "巴基斯坦": "Pakistan",
    "孟加拉国": "Bangladesh",
    "斯里兰卡": "Sri Lanka",
    "尼泊尔": "Nepal",
    "马尔代夫": "Maldives",
    "不丹": "Bhutan",
    # ── Oceania ──
    "澳大利亚": "Australia",
    "新西兰": "New Zealand",
    "斐济": "Fiji",
    "巴布亚新几内亚": "Papua New Guinea",
    "关岛": "Guam",
    "萨摩亚": "Samoa",
    "汤加": "Tonga",
    "瓦努阿图": "Vanuatu",
    "库克群岛": "Cook Islands",
    "法属波利尼西亚": "French Polynesia",
    "马绍尔群岛": "Marshall Islands",
    "密克罗尼西亚": "Micronesia",
    "帕劳": "Palau",
    "北马里亚纳群岛": "Northern Mariana Islands",
    "新喀里多尼亚": "New Caledonia",
    # ── Western Europe ──
    "德国": "Germany",
    "法国": "France",
    "英国": "United Kingdom",
    "意大利": "Italy",
    "西班牙": "Spain",
    "荷兰": "Netherlands",
    "比利时": "Belgium",
    "卢森堡": "Luxembourg",
    "瑞士": "Switzerland",
    "奥地利": "Austria",
    "爱尔兰": "Ireland",
    "摩纳哥": "Monaco",
    "安道尔": "Andorra",
    "直布罗陀": "Gibraltar",
    "梵蒂冈城": "Vatican City",
    "圣马力诺": "San Marino",
    "马耳他": "Malta",
    "列支敦士登": "Liechtenstein",
    # ── Northern Europe ──
    "瑞典": "Sweden",
    "丹麦": "Denmark",
    "挪威": "Norway",
    "芬兰": "Finland",
    "冰岛": "Iceland",
    "爱沙尼亚": "Estonia",
    "拉脱维亚": "Latvia",
    "立陶宛": "Lithuania",
    "格陵兰岛": "Greenland",
    "法罗群岛": "Faroe Islands",
    # ── Eastern Europe ──
    "波兰": "Poland",
    "捷克共和国": "Czech Republic",
    "匈牙利": "Hungary",
    "罗马尼亚": "Romania",
    "保加利亚": "Bulgaria",
    "克罗地亚": "Croatia",
    "斯洛文尼亚": "Slovenia",
    "斯洛伐克共和国": "Slovakia",
    "塞尔维亚": "Serbia",
    "乌克兰": "Ukraine",
    "白俄罗斯": "Belarus",
    "摩尔多瓦": "Moldova",
    "波黑": "Bosnia and Herzegovina",
    "北马其顿": "North Macedonia",
    "阿尔巴尼亚": "Albania",
    "黑山共和国": "Montenegro",
    "亚美尼亚": "Armenia",
    "阿塞拜疆": "Azerbaijan",
    "格鲁吉亚": "Georgia",
    "俄罗斯": "Russia",
    # ── Middle East ──
    "阿联酋": "United Arab Emirates",
    "沙特阿拉伯": "Saudi Arabia",
    "卡塔尔": "Qatar",
    "科威特": "Kuwait",
    "巴林": "Bahrain",
    "阿曼": "Oman",
    "约旦": "Jordan",
    "以色列": "Israel",
    "土耳其": "Turkey",
    "黎巴嫩": "Lebanon",
    "伊拉克": "Iraq",
    "叙利亚": "Syria",
    "也门": "Yemen",
    "伊朗": "Iran",
    "阿富汗": "Afghanistan",
    "塞浦路斯": "Cyprus",
    "巴勒斯坦自治地区": "Palestine",
    # ── Africa ──
    "南非": "South Africa",
    "埃及": "Egypt",
    "摩洛哥": "Morocco",
    "尼日利亚": "Nigeria",
    "肯尼亚": "Kenya",
    "加纳": "Ghana",
    "阿尔及利亚": "Algeria",
    "安哥拉": "Angola",
    "贝宁": "Benin",
    "博茨瓦纳": "Botswana",
    "布基纳法索": "Burkina Faso",
    "布隆迪": "Burundi",
    "喀麦隆": "Cameroon",
    "佛得角": "Cape Verde",
    "乍得": "Chad",
    "刚果": "Congo",
    "刚果民主共和国": "DR Congo",
    "吉布提": "Djibouti",
    "厄立特里亚": "Eritrea",
    "埃塞俄比亚": "Ethiopia",
    "加蓬": "Gabon",
    "冈比亚": "Gambia",
    "几内亚": "Guinea",
    "科特迪瓦": "Ivory Coast",
    "莱索托": "Lesotho",
    "利比里亚": "Liberia",
    "利比亚": "Libya",
    "马达加斯加": "Madagascar",
    "马拉维": "Malawi",
    "马里": "Mali",
    "毛里塔尼亚": "Mauritania",
    "毛里求斯": "Mauritius",
    "莫桑比克": "Mozambique",
    "纳米比亚": "Namibia",
    "尼日尔": "Niger",
    "卢旺达": "Rwanda",
    "塞内加尔": "Senegal",
    "塞舌尔": "Seychelles",
    "塞拉利昂": "Sierra Leone",
    "索马里": "Somalia",
    "南苏丹": "South Sudan",
    "苏丹": "Sudan",
    "斯威士兰": "Eswatini",
    "坦桑尼亚": "Tanzania",
    "多哥": "Togo",
    "突尼斯": "Tunisia",
    "乌干达": "Uganda",
    "赞比亚": "Zambia",
    "津巴布韦": "Zimbabwe",
    "赤道几内亚": "Equatorial Guinea",
    "留尼汪岛": "Reunion",
    # ── Americas ──
    "美国": "United States",
    "加拿大": "Canada",
    "墨西哥": "Mexico",
    "巴西": "Brazil",
    "阿根廷": "Argentina",
    "智利": "Chile",
    "秘鲁": "Peru",
    "哥伦比亚": "Colombia",
    "委内瑞拉": "Venezuela",
    "厄瓜多尔": "Ecuador",
    "玻利维亚": "Bolivia",
    "巴拉圭": "Paraguay",
    "乌拉圭": "Uruguay",
    "哥斯达黎加": "Costa Rica",
    "巴拿马": "Panama",
    "危地马拉": "Guatemala",
    "洪都拉斯": "Honduras",
    "萨尔瓦多": "El Salvador",
    "尼加拉瓜": "Nicaragua",
    "多米尼加共和国": "Dominican Republic",
    "牙买加": "Jamaica",
    "特立尼达和多巴哥": "Trinidad and Tobago",
    "巴巴多斯": "Barbados",
    "巴哈马": "Bahamas",
    "海地": "Haiti",
    "古巴": "Cuba",
    "波多黎各": "Puerto Rico",
    # ── Central Asia ──
    "哈萨克斯坦": "Kazakhstan",
    "乌兹别克斯坦": "Uzbekistan",
    "塔吉克斯坦": "Tajikistan",
    "吉尔吉斯斯坦": "Kyrgyzstan",
    "土库曼斯坦": "Turkmenistan",
    # ── Pacific islands / special ──
    "美属萨摩亚": "American Samoa",
    "海峡群岛": "Channel Islands",
    "加那利群岛": "Canary Islands",
    "塔希提岛": "Tahiti",
    "塞班岛": "Saipan",
    "天宁岛": "Tinian",
    "罗塔岛": "Rota",
    "瓦利斯和富图纳群岛": "Wallis and Futuna",
}


def to_english(cn_name: str) -> str:
    """Translate a Chinese country name to English. Falls back to CN if unknown."""
    return CN_TO_EN.get(cn_name, cn_name)
