import {writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
export const nav=[['index.html','Home'],['courses.html','Courses'],['learner-information.html','For learners'],['employers.html','For employers'],['centre.html','Our centre'],['enquiry.html','Plan an enquiry']];
export const img=(name,alt,extra='')=>`<img src="assets/${name}.webp" srcset="assets/${name}-768.webp 768w, assets/${name}.webp 1536w" sizes="(max-width:700px) 100vw, 65vw" width="1536" height="1024" alt="${alt}" ${extra}>`;
export const button=(href,label,light=false)=>`<a class="button${light?' light':''}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
export const intro=(eyebrow,title,text)=>`<div class="page-intro"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p></div>`;
export const cta=(title='A useful next step starts with the right course.')=>`<div class="cta"><h2>${title}</h2>${button('enquiry.html','Plan an enquiry')}</div>`;
const version=createHash('sha256').update(await readFile(new URL('site.css',import.meta.url))).digest('hex').slice(0,8);
export async function page(path,title,description,body){
await writeFile(new URL(path,import.meta.url),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${description}"><meta name="theme-color" content="#172d3b"><title>${title} | Northspan Skills</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="assets/fonts/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="site.css?v=${version}"><script type="module" src="app.js?v=${version}"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-inner wrap"><a class="brand" href="index.html" aria-label="Northspan Skills home"><span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>northspan<small>skills</small></span></a><nav class="site-nav" aria-label="Main navigation">${nav.map(([href,label])=>`<a href="${href}"${href===path?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header><main id="main" tabindex="-1">${body}</main><footer class="site-footer"><div class="wrap"><div class="footer-top"><div><a class="brand" href="index.html">northspan <small>skills</small></a><p>Practical short courses for adults and local teams.<br>Birmingham, UK · Established 2019</p></div><div><nav class="footer-nav" aria-label="Footer navigation"><a href="courses.html">All three courses</a><a href="learner-information.html">Getting ready</a><a href="centre.html">The centre</a></nav><p class="small">Monday–Friday, 09:00–17:00<br>Example contact: learning@northspan.example</p></div></div><div class="disclosure"><p id="concept">Fictional training centre / concept website. Course dates, fees, people and facilities are illustrative. Images are original generated scenes. No live places, payments, qualifications or job guarantees. The enquiry tool stays on the current page; nothing is sent or stored.</p><a href="/#work" data-showcase>Return to Showcase ↗</a></div></div></footer></body></html>`,'utf8');
}
