export const journeys=[
 {id:'inland',file:'inland-spain.html',image:'inland',name:'Inland Spain',region:'Madrid & Segovia',tag:'Art, stone & long lunches',bases:['Madrid','Segovia'],nights:[3,4],mode:'Rail between bases',move:'A proposed Renfe rail connection from Madrid to Segovia. Plan city-to-station and station-to-stay journeys separately; exact services and tickets need checking for your dates.',intro:'Start with the scale of Madrid, then give a smaller city a little more of your time. Seven nights, two bases and a single change of scene.',why:'The move is part of the journey, not something squeezed between two booked visits. Three nights in Madrid leave room for one collection and a neighbourhood morning; four in Segovia let the old town become familiar.',suits:'Couples and families who like city culture, food and time to wander. Best for a first conversation about two settled bases rather than a list of Spain-wide highlights.',trade:'It leaves out Barcelona, Andalusia and the coast. Walking surfaces, room access and individual needs must be discussed before any stay or visit is selected.',alt:'A generated inland Spanish regional scene: a warm stone lane, shutters, balconies and a small cafe table in the morning shade.',caption:'Stone, shade and a table for two. Original regional illustration.',source:'https://www.renfe.com/es/en/inspirate/rutas/madrid-segovia',sourceLabel:'Renfe: Madrid–Segovia connection',days:[
 ['Arrive in Madrid','Madrid','Arrival','Keep the arrival day light. Reach your chosen stay, find a nearby place for supper and leave visits until you know how you feel.'],
 ['One collection, properly','Madrid','Art & history','Choose one art collection to spend time with, with entry arrangements checked separately. Leave the rest of the day for a neighbourhood walk or an earlier finish.'],
 ['A morning around the market','Madrid','Food & time open','Set aside a morning for independent food stops and the streets around them. The afternoon has no booked activity in this sample.'],
 ['Change city, keep the day clear','Segovia','Rail transfer','Take the proposed Madrid–Segovia rail connection when a suitable service is confirmed. Allow for station access and settling in; do not attach a timed visit to the transfer day.'],
 ['Read the city in stone','Segovia','Old town','Begin around the aqueduct and continue into the old town at a pace that suits you. Decide the extent of the walk locally; this is not a mapped walking route.'],
 ['The city at lunchtime','Segovia','Food & time open','A locally paced food morning, with your table choices made independently. Leave the afternoon for a return to somewhere you liked.'],
 ['A day without a list','Segovia','Open day','Keep this day genuinely unallocated. Stay near your base, repeat a favourite walk or rest. An extra excursion is not required to make the day worthwhile.'],
 ['Leave room for the onward journey','Segovia','Departure','Check your actual onward transport, transfers and check-out arrangements. This sample does not assume an airport connection or include a ticket.']
 ],activities:[{food:[['A market neighbourhood morning','Explore a Madrid market neighbourhood and choose a few independent food stops.'],['A second table, a different district','Choose one new neighbourhood for a leisurely lunch rather than crossing the city for a long checklist.']],culture:[['One Madrid collection','Choose a single art collection and discuss entry arrangements separately.'],['Plazas and neighbourhood detail','Spend a morning looking at the buildings, bookshops and everyday streets around your chosen base.']],outside:[['A green pause in the city','Choose one city park and a nearby neighbourhood stroll, with the walking distance discussed first.'],['A different neighbourhood on foot','Keep a second city walk local to the stay area and leave a place to pause.']]},{food:[['Segovia at lunchtime','Make time for a locally paced food morning and independent lunch choice.'],['Return to a favourite table','Keep the food focus close to your base, with a new bakery or lunch stop chosen on the day.']],culture:[['Aqueduct and old-town detail','Begin around the Segovia aqueduct, then choose a comfortable extent of old-town streets.'],['One local collection','Discuss a single local collection or interior visit, checking admission and opening separately.']],outside:[['An old-town wander','Take a short walk from the chosen stay area with the distance and surface considered first.'],['A slower second look','Return to a familiar square and add only a modest new section if it suits the group.']]}]},
 {id:'north',file:'northern-coast.html',image:'coast',name:'Northern Coast',region:'Bilbao & San Sebastián',tag:'Riversides, pintxos & bay walks',bases:['Bilbao','San Sebastián'],nights:[3,4],mode:'Road transfer between bases',move:'A proposed road transfer between Bilbao and San Sebastián, arranged separately with a selected licensed provider. The studio does not operate vehicles or include a transfer reservation.',intro:'The river first, the bay next. A week between Bilbao and Donostia / San Sebastián, with enough space around the food and city walks to make each place your own.',why:'Three nights in Bilbao make room for its river and a chosen collection. A single move leads to four nights in San Sebastián, where the bay and neighbourhood food can be enjoyed without changing stays again.',suits:'Travellers who want food, city character and time near the sea. Families can trade a second outing for a rest break without unpicking the whole route.',trade:'This is not a beach resort booking or a promise of swimming weather. Outdoor plans need a local conditions check and an indoor alternative. The inter-base movement is road-led, not a rail itinerary.',alt:'A generated Basque-coast regional scene with a pale walking terrace, curving bay, blue-green water and a wooded headland.',caption:'A little more time beside the water. Original regional illustration.',source:'https://sansebastianturismoa.eus/en/to-do/let-s-go-to-the-beach/la-concha-beach/the-concha-bay/',sourceLabel:'San Sebastián Tourism: La Concha bay',days:[
 ['Arrive beside the river','Bilbao','Arrival','Settle into your selected stay area. Keep only a short orientation in mind, with no timed activity tied to the arrival journey.'],
 ['Architecture and one collection','Bilbao','City culture','Spend a morning on riverside architecture and choose one collection if it appeals. Admission, opening and any guiding would be arranged separately.'],
 ['Food at neighbourhood pace','Bilbao','Food & time open','Make a few independent food stops, with a table or quiet break between them. The afternoon remains yours.'],
 ['From river to bay','San Sebastián','Road transfer','Move between the two bases using a separately arranged road transfer. Check provider and actual pickup details before travel; spend the rest of the day settling in.'],
 ['Follow the bay for a while','San Sebastián','Bay walk','Consider part of La Concha bay at a suitable walking pace. Check local conditions and keep an indoor collection or cafe pause available as an alternative.'],
 ['A morning led by food','San Sebastián','Food & time open','Explore neighbourhood food with the number of stops chosen around your appetite. No restaurant reservation or tasting is included in this sample.'],
 ['Keep the day open','San Sebastián','Open day','Go back to a part of the city you enjoyed, rest near the stay, or choose an independent local outing. There is no required additional destination.'],
 ['Onward, with time allowed','San Sebastián','Departure','Confirm your own onward service, pickup and luggage arrangements. No transfer time or airport connection is promised here.']
 ],activities:[{food:[['Bilbao, one bite at a time','Build a short sequence of neighbourhood food stops with time for a proper pause.'],['A market-area lunch','Choose a market-area lunch and leave the afternoon near the river.']],culture:[['Riverside architecture','Spend time on Bilbao riverside architecture and decide whether to add one collection.'],['One chosen collection','Focus on a single museum or gallery, with opening and admission checked separately.']],outside:[['An easy river orientation','Choose a short riverside section and a place to pause; check surfaces and distance for your group.'],['A second neighbourhood stroll','Explore a new neighbourhood without leaving a large travel gap between stops.']]},{food:[['Food in San Sebastián','Choose a few neighbourhood food stops; a tasting or restaurant reservation is not assumed.'],['A table with time around it','Keep lunch as the main event and leave the rest of the day within an easy return of your stay.']],culture:[['City detail around the old town','Choose a short old-town exploration and one interior visit if it suits your interests.'],['A collection and a cafe pause','Discuss a single local collection and allow space for conversation afterwards.']],outside:[['A stretch of La Concha bay','Choose part of the bay walk, checking local conditions and an indoor alternative.'],['Return to the water','Spend another short period near the bay rather than adding a distant coastal excursion.']]}]},
 {id:'rail',file:'two-cities-by-rail.html',image:'portugal',name:'Two Cities by Rail',region:'Lisbon & Porto',tag:'City corners & a single train journey',bases:['Lisbon','Porto'],nights:[3,4],mode:'Rail between bases',move:'A proposed CP long-distance rail connection between Lisbon and Porto. Check the exact stations, travel dates, train, seats and onward connections with CP before purchasing anything.',intro:'A Lisbon street that makes you slow down. A Porto afternoon with no next appointment. Two cities, one rail link and time to notice the everyday details.',why:'The route avoids changing stays each night. Three nights in Lisbon create a settled beginning; four in Porto leave a full open day after the intercity move.',suits:'Couples and families curious about city life, architecture and food. A good starting point when one rail journey appeals more than a car-led multi-region itinerary.',trade:'This stays with Lisbon and Porto. It does not include the Douro Valley, Algarve or a day trip to every nearby sight. Walking distances, slopes and accommodation access must be discussed; accessibility is never assumed from a city name.',alt:'A generated Portuguese neighbourhood scene with a pale yellow facade, blue-and-white tile, balcony and small outdoor table.',caption:'The useful pleasure of taking a side street. Original regional illustration.',source:'https://www.cp.pt/info/documents/d/cp/comboios-alfa-pendular-intercidades-lisboa-norte-sul-1',sourceLabel:'CP: Lisbon–Porto long-distance line',days:[
 ['Arrive in Lisbon','Lisbon','Arrival','Reach the chosen neighbourhood and settle in. A nearby meal is enough of a plan for the first evening; no timed visit depends on arrival.'],
 ['Look at the small things','Lisbon','Streets & design','Give a morning to the street detail, tiles and buildings around one neighbourhood. Discuss a suitable walk and where to pause before fixing the route.'],
 ['A food morning, an open afternoon','Lisbon','Food & time open','Make a small set of independent food stops, with the afternoon left open. A restaurant booking or guided tasting is not part of the sample.'],
 ['One rail journey north','Porto','Rail transfer','Take a suitable CP connection once dates and seats have been verified. Allow time for both station journeys and settling into the second base.'],
 ['The city beside the river','Porto','Riverside','Choose a manageable riverside walk and one place to stop. Walking surfaces, slopes and access need individual consideration.'],
 ['One collection and time around it','Porto','Art & craft','Choose an art or craft collection to explore, with admission checked separately. Leave the remainder of the day near your base.'],
 ['Nothing fixed in the diary','Porto','Open day','Return to a favourite street, have a longer lunch or simply rest. This route does not need a last-minute day trip to be complete.'],
 ['Continue from Porto','Porto','Departure','Check your actual onward tickets and any station or airport journey separately. No connection, transfer or departure time is included.']
 ],activities:[{food:[['A Lisbon food neighbourhood','Choose a few independent food stops within one neighbourhood, with time to sit down.'],['One lunch, no rush','Make a leisurely lunch the main focus and leave nearby streets for afterwards.']],culture:[['Lisbon street and tile detail','Spend a morning on street, tile and building details in one selected neighbourhood.'],['A single city collection','Discuss an art or design collection and check its actual opening and admission before travel.']],outside:[['A neighbourhood on foot','Choose a walk and stopping places that suit your group, considering slopes and surfaces.'],['A local pause in the open air','Leave time for one nearby open space without planning a cross-city sequence.']]},{food:[['Porto around the table','Make independent food stops within a small area and allow time for a proper meal.'],['A second neighbourhood for lunch','Choose another local table, with the remainder of the day close to your base.']],culture:[['One Porto collection','Focus on an art or craft collection, with opening and admission confirmed separately.'],['Buildings and neighbourhood stories','Take a short architecture-led walk with a manageable extent agreed first.']],outside:[['A Porto riverside walk','Choose a riverside section and a place to rest, with access and surfaces considered.'],['A slower return to the river','Return to a favourite section rather than adding a distant excursion.']]}]}
];
