export const money=value=>'A$'+new Intl.NumberFormat('en-AU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value);
export const hours=value=>`${value} ${value===1?'hour':'hours'}`;
export const vehicles={small:{name:'Small',description:'Hatchback or compact sedan; up to five seats.'},medium:{name:'Medium',description:'Larger sedan or five-seat crossover.'},large:{name:'Large',description:'Seven-seat SUV or dual-cab ute; tray excluded.'},other:{name:'Outside standard range',description:'Van, camper conversion or heavy commercial vehicle.'}};
export const packages={
 cabin:{name:'Cabin Reset',short:'For the space you sit in.',area:'Interior',description:'A practical clean of the accessible cabin: the dust in the footwell, crumbs around the seats and the marks on everyday touchpoints. Bring the car with personal belongings removed so we can agree what is accessible.',prices:{small:[145,2],medium:[175,2.5],large:[215,3]},included:['Vacuum accessible seats, floor and empty boot','Wipe accessible interior hard surfaces','Clean interior glass','Clean removable floor mats'],excluded:['Seat removal or wet upholstery extraction','Headlining treatment or child-seat removal/reinstallation','Mould or biohazard cleanup','Guaranteed stain or odour removal'],conditions:[{id:'routine',label:'Routine dust and crumbs'},{id:'review',label:'Heavy pet hair or embedded spills'}],limit:'Heavy pet hair or embedded spills need a separate inspection. We do not automatically add a surcharge or promise a result.',photo:'A gloved detailer dry-vacuums an accessible passenger footwell.',prepare:'Remove loose belongings and empty the boot. We do not remove or reinstall child seats; any areas they block stay outside the clean.'},
 wash:{name:'Wash & Protect',short:'An exterior visit, clearly defined.',area:'Exterior',description:'A hand wash and dry for an everyday gloss-painted car, followed by spray sealant on suitable painted panels. We check the finish before choosing products or starting work.',prices:{small:[110,1.5],medium:[135,2],large:[165,2.5]},included:['Exterior hand wash','Accessible wheel faces','Drying and exterior glass','Spray sealant on compatible painted panels'],excluded:['Interior, underside, engine bay or ute tray','Machine polishing or scratch removal','Matte paint or vinyl-wrap treatment','Coating-life or finish guarantee'],conditions:[{id:'routine',label:'Ordinary gloss paint, no known damage'},{id:'review',label:'Matte finish, vinyl wrap or known paint damage'}],limit:'Matte finishes, vinyl wrap or known damage need inspection first. The online worksheet does not confirm product compatibility.',photo:'A gloved hand washes the side panel of a silver car with a microfibre mitt.',prepare:'Remove detachable personal items from the exterior if appropriate. Tell the workshop about any known finish changes or damage before work.'},
 surface:{name:'Surface Refresh',short:'Make time to consider the finish.',area:'Exterior enhancement',description:'A more involved exterior visit with preparation, inspection and a small test area before one-stage machine enhancement on compatible gloss paint. The agreed aim is a considered refresh, not the removal of every mark.',prices:{small:[325,4],medium:[395,5],large:[475,6]},included:['Exterior wash and appropriate preparation','Paint inspection and a small test area','One-stage machine enhancement on compatible gloss paint','Hand finish and spray sealant application'],excluded:['Interior cleaning or multi-stage correction','Respray, touch-up or deep-scratch repair','Paint protection film installation','All-defect removal or coating-life guarantee'],conditions:[{id:'routine',label:'Ordinary gloss paint, no known damage'},{id:'review',label:'Matte finish, vinyl wrap or known paint damage'}],limit:'The physical inspection and test area decide whether the work is suitable. Matte finishes, vinyl wrap and known damage are inspection-only here.',photo:'A technician checks a gloss panel with a handheld inspection light before treatment.',prepare:'Allow time for a walk-around and paint discussion. A photograph or description alone cannot establish what the finish will tolerate.'}
};
export const preferences={morning:'Weekday morning',afternoon:'Weekday afternoon',flexible:'Flexible weekday'};
