import {visits} from './data.js';
const form=document.querySelector('#enquiry-form');
if(form){
 const fields={visit:form.elements.namedItem('visit'),relationship:form.elements.namedItem('relationship'),visitor:form.elements.namedItem('visitor'),setting:form.elements.namedItem('setting'),time:form.elements.namedItem('time')};
 const maps={relationship:{new:'First visit to the practice',returning:'Returning to the practice'},visitor:{adult:'An adult visit',child:'A child with a parent or guardian'},setting:{usual:'Usual arrival arrangements',ground:'Ask about a ground-floor room',quiet:'Ask about a quieter arrival'},time:{morning:'Monday–Thursday morning',afternoon:'Monday–Thursday afternoon',friday:'Friday morning'}};
 const settingNotes={usual:'Confirm the actual arrival arrangements with the practice before setting off.',ground:'Ask whether the ground-floor consultation room can be arranged. The upper rooms require stairs. This request is not a room allocation.',quiet:'Ask a coordinator about a quieter arrival and the available arrangements. A quieter setting or time is not guaranteed.'};
 const query=new URLSearchParams(location.search),visitQuery=query.get('visit'),settingQuery=query.get('setting');if(visits.some(v=>v.id===visitQuery)||visitQuery==='unsure')fields.visit.value=visitQuery;if(Object.hasOwn(maps.setting,settingQuery))fields.setting.value=settingQuery;
 const result=document.querySelector('#plan-result'),error=document.querySelector('#form-error');let note='';
 const details=()=>{const visit=visits.find(v=>v.id===fields.visit.value);return {visit,title:visit?.name||(fields.visit.value==='unsure'?'Not sure — a first conversation':'Choose a visit to begin.'),preparation:visit?.preparation||'Ask the coordinator to explain the three visit types before choosing a visit. This website cannot assess clinical needs.'};};
 const update=()=>{note='';result.hidden=true;error.textContent='';const d=details();document.querySelector('#preview-visit').textContent=d.title;document.querySelector('#preview-note').textContent=d.preparation;for(const name of ['relationship','visitor','setting','time'])document.querySelector('#preview-'+name).textContent=maps[name][fields[name].value]||'Not selected';};
 update();form.addEventListener('change',update);form.addEventListener('input',()=>{note='';result.hidden=true;});
 form.addEventListener('submit',event=>{event.preventDefault();update();if(!form.reportValidity()){error.textContent='Choose a visit and contact preference, then confirm the demonstration acknowledgement.';return;}if(![...visits.map(v=>v.id),'unsure'].includes(fields.visit.value)||Object.keys(maps).some(name=>!Object.hasOwn(maps[name],fields[name].value))){error.textContent='Choose one of the listed preferences to continue.';return;}const d=details();const start=fields.relationship.value==='new'?'Ask how first-visit arrival and paperwork are handled in a real practice. Clinical information belongs in a private conversation with the actual provider.':'Confirm the purpose of a returning visit with the actual practice. This demonstration cannot access previous visits or records.';const visitor=fields.visitor.value==='child'?'A parent or guardian should discuss the actual visit arrangements with the practice and accompany the child. No child identity or health information is collected here.':'This is an adult-visit enquiry outline. No identity or health information is collected here.';note=['WILLOWGATE DENTAL / CONVERSATION NOTE','Fictional non-urgent demonstration. Not sent; no appointment booked.',`Visit: ${d.title}`,`Starting point: ${maps.relationship[fields.relationship.value]}`,`Visitor: ${maps.visitor[fields.visitor.value]}`,`Setting request: ${maps.setting[fields.setting.value]}`,`Contact preference: ${maps.time[fields.time.value]} (unconfirmed)`,'','TO DISCUSS',d.preparation,start,visitor,settingNotes[fields.setting.value],'','No clinical advice, treatment choice, fee quote, appointment allocation or callback is provided.','Current-page choices only. No personal details collected, stored or transmitted.'].join('\n');document.querySelector('#plan-lines').textContent=note;result.hidden=false;result.focus();});
 document.querySelector('#clear-plan').addEventListener('click',()=>{form.reset();update();error.textContent='Choices cleared. Any link preset is applied again only if you reload this URL.';fields.visit.focus();});
 document.querySelector('#edit-plan').addEventListener('click',()=>{update();fields.visit.focus();});
 document.querySelector('#download-plan').addEventListener('click',()=>{if(!note||result.hidden)return;const url=URL.createObjectURL(new Blob([note],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='willowgate-conversation-note.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}
