export const projects=[
 {id:'design-week-room',name:'Design Week Room',number:'01',format:'Materials exhibition',area:'180 m²',space:'Indoor workshop',audience:'Design-aware visitors and local makers',tone:'orange',brief:'Make the work behind a finished object visible.',summary:'A material library, an open making table and a conversation with the people who make things.',commission:'An imagined local maker collective wants its materials and methods to be as memorable as its finished pieces. The room invites a visitor to compare, try and ask, without relying on a long introductory talk.',response:'An orange arrival frame opens a view through the room. Low sample plinths leave the making table visible beyond them; the conversation area sits to one side so that a longer discussion can happen without becoming the only way through.',package:'Content hierarchy, station layouts, sample labels, a table activity script and a host handover. A specialist fabricator would develop the temporary joinery and a venue team would confirm installation conditions.',boundary:'The maker collective would approve object information and handling permissions. The venue and appointed specialists would resolve actual dimensions, capacity, access, structure and operations.',positions:[[65,245],[145,115],[280,90],[405,150],[390,260]],stations:[
  {name:'Arrival frame',action:'Read the room question and choose where to begin.',owner:'Host: introduce the material story.'},
  {name:'Material library',action:'Compare three sample families by texture, finish and intended use.',owner:'Content lead: approve labels and object handling.'},
  {name:'Assembly table',action:'Follow a simple component sequence with a host explaining the choices.',owner:'Activity host: guide the demonstration and reset the table.'},
  {name:'Maker conversation',action:'Use a prompt card to ask about a material or making decision.',owner:'Maker host: discuss the work without a sales script.'},
  {name:'Take-away shelf',action:'Choose a printed material note to continue the story after leaving.',owner:'Host: maintain the take-away stock.'}
 ]},
 {id:'launch-courtyard',name:'Launch Courtyard',number:'02',format:'Homeware pop-up',area:'120 m²',space:'Courtyard concept',audience:'Invited trade visitors and interested neighbours',tone:'lilac',brief:'Give a small collection enough room to be understood.',summary:'A product island and a working demonstration bar, with space for an unhurried conversation.',commission:'An invented independent homeware team is introducing a small ceramic collection. It needs a temporary setting where people can look closely, see how pieces are used and talk to a host before deciding what to explore next.',response:'A low orange product island establishes the first focal point. A demonstration bar sits behind it, while a host table at the planted edge supports a longer conversation. The arrival and departure notes stay separate from the product display.',package:'Product display hierarchy, a demonstration sequence, host prompts, arrival graphics and a supplier handover. Temporary furniture, lighting and any canopy would require a venue-specific specialist design.',boundary:'The brand would approve product information and samples. Weather, an indoor fallback, surface conditions, any overhead elements and the real operating plan would be resolved before an outdoor installation is agreed.',positions:[[70,250],[195,150],[345,65],[425,215],[230,260]],stations:[
  {name:'Arrival desk',action:'Meet the host and understand the small collection being introduced.',owner:'Host: separate arrival information from a product conversation.'},
  {name:'Product island',action:'Look closely at form, glaze and the relationship between pieces.',owner:'Brand content owner: confirm sample information and handling.'},
  {name:'Demonstration bar',action:'Watch a host show how the pieces fit into a table setting.',owner:'Demonstrator: prepare, present and reset the display.'},
  {name:'Host table',action:'Discuss a use case or question with the collection team.',owner:'Brand host: answer approved product questions.'},
  {name:'Departure note',action:'Take a collection overview and choose an independent next step.',owner:'Host: offer the printed overview without collecting details.'}
 ]},
 {id:'community-archive',name:'Community Archive',number:'03',format:'Neighbourhood exhibition',area:'90 m²',space:'Small indoor gallery',audience:'A mixed local audience',tone:'cream',brief:'Let ordinary objects hold the centre of the story.',summary:'A small archive of imagined everyday objects, with room to look, listen and share a thought.',commission:'An invented cultural team wants to build a temporary exhibition around the ordinary things a neighbourhood keeps. The concept gives a cup, key and cloth their own context without claiming real provenance or recording personal histories online.',response:'A compact guide introduces the room. Objects sit beside concise captions, a listening desk provides one content mode and a shared table creates a separate place for conversation. A reflection wall closes the visit without making participation compulsory.',package:'Story structure, object/caption schedule, listening-content outline, table prompts and a host brief. Display cases, audio equipment and installation would be resolved with appropriate suppliers and the venue.',boundary:'In a real project the content owner would clear object loans, image/audio rights and any consent process before use. All objects, voices and histories here are invented; the website collects no memories or guest information.',positions:[[65,70],[200,80],[420,105],[310,225],[95,250]],stations:[
  {name:'Room guide',action:'Read the exhibition question and the available ways to explore.',owner:'Host: introduce the content without requiring participation.'},
  {name:'Object display',action:'Look at an everyday object and its short, imagined context.',owner:'Content owner: verify provenance and permissions in a real project.'},
  {name:'Listening desk',action:'Explore the outline of an audio story, with a text alternative planned.',owner:'Content lead: prepare and clear audio and transcript material.'},
  {name:'Shared-memory table',action:'Use a fictional prompt to discuss what an ordinary object can carry.',owner:'Facilitator: support an optional conversation and agreed consent process.'},
  {name:'Reflection wall',action:'Leave with a question to notice in the everyday world.',owner:'Host: explain that contributing is optional.'}
 ]}
];
export const emphasisLabels={objects:'Look at objects',process:'Understand the process',conversation:'Make room for conversation'};
export function pathChoice(projectId='design-week-room',duration=20,emphasis='objects'){
 const project=projects.find(p=>p.id===projectId)||projects[0];const focus={objects:1,process:2,conversation:3}[emphasis]||1;const total=duration===40?40:20;
 const order=total===20?[0,focus,4]:[0,focus,...[1,2,3].filter(i=>i!==focus),4];
 const stops=order.map((index,i)=>({...project.stations[index],index,minutes:i===0||i===order.length-1?3:total===20?14:index===focus?16:9}));
 return {project,emphasis:emphasisLabels[emphasis]?emphasis:'objects',total,stops};
}
export function pathText(choice){return ['GATHERLINE PROJECTS / LOCAL VISITOR CONTENT NOTE','Fictional project: '+choice.project.name,'Emphasis: '+emphasisLabels[choice.emphasis],'Illustrative content time: '+choice.total+' minutes','',...choice.stops.map((s,i)=>(i+1)+'. '+s.name+' - '+s.minutes+' min\n'+s.action+'\n'+s.owner),'','Times exclude walking, queues, assistance and venue operations. Diagram is not to scale, not for navigation, access assurance or life-safety planning. No event, ticket, booking or message is created. Choices remain only on this page; this downloaded file stays on your device.'].join('\n');}
export const formats={
 exhibition:{label:'Temporary exhibition',min:8,max:12,direction:'A story told through objects and content stations.',sequence:'Arrival question → object encounter → deeper content → optional exchange → closing reflection.',package:'A content hierarchy, object/caption schedule, station layouts and a host handover.'},
 popup:{label:'Brand pop-up',min:6,max:10,direction:'A small collection introduced through use and conversation.',sequence:'Arrival introduction → product focus → demonstration → host conversation → take-away overview.',package:'A display hierarchy, demonstration script, host prompts and a temporary installation brief.'},
 gathering:{label:'Small gathering',min:5,max:8,direction:'A shared question with room for both a group moment and smaller conversations.',sequence:'Hosted arrival → opening question → shared activity → small-group discussion → closing note.',package:'A programme outline, hosting brief, room sequence and supplier coordination schedule.'}
};
export const audienceLabels={professional:'Professional audience',public:'Public audience',mixed:'Mixed audience'};
export const spaceLabels={indoor:'Indoor space identified',courtyard:'Courtyard or outdoor space',unknown:'Space not confirmed'};
export function briefChoice(format,audience,visitors,space,weeks){
 const offer=formats[format];const issues=[];
 if(visitors>200)issues.push('The intended '+visitors+' visitors exceed our usual 20–200 programme discussion scope. Establish a smaller pilot or a separately staffed scope before detailed design. This is not a capacity assessment.');
 if(weeks<offer.min)issues.push('The '+weeks+'-week lead time is shorter than our '+offer.min+'–'+offer.max+'-week starting discussion window for this format. Reduce or phase the scope before treating a delivery programme as viable.');
 if(space==='unknown')issues.push('The space is not confirmed. Obtain venue information and a named venue contact before treating any layout as ready to develop.');
 const spaceNote=space==='courtyard'?'Resolve a weather decision point and an indoor fallback with the venue. Surface, power and any overhead elements need specialist review; no outdoor installation is approved here.':space==='indoor'?'Collect the venue information, installation conditions and operating responsibilities. An identified room is not confirmation of access, capacity or technical suitability.':'First establish the broad venue type, available information and operational owner. No plan can confirm an unidentified space.';
 const audienceNote={professional:'Prepare a concise subject introduction, deeper technical prompts and a host able to discuss approved detail.',public:'Plan a clear welcome, plain-language captions and multiple ways to encounter the content. Agree appropriate hosting and content permissions.',mixed:'Separate a clear first encounter from optional deeper content. Brief hosts to support different interests and agree alternative content formats.'}[audience];
 const title=issues.length?'Resolve the scope before the room.':'Your first spatial brief.';
 return {format,audience,visitors,space,weeks,offer,issues,spaceNote,audienceNote,title};
}
export function briefText(c){return ['GATHERLINE PROJECTS / LOCAL PROJECT BRIEF','Fictional studio. Nothing sent, scheduled, purchased or approved.','',c.offer.label+' / '+audienceLabels[c.audience],'Intended visitors over the programme: '+c.visitors+' (not concurrent capacity)','Space: '+spaceLabels[c.space],'Lead time to discuss: '+c.weeks+' weeks','Starting planning window: '+c.offer.min+'–'+c.offer.max+' weeks, subject to scope and separate agreement','',c.title,...c.issues,'',c.offer.direction,c.offer.sequence,c.offer.package,'',c.audienceNote,c.spaceNote,'','Client: approve content, appoint venue contact and own the actual guest/consent arrangements.','Gatherline: develop the story, content sequence and agreed production coordination.','Venue and specialists: confirm actual site conditions, technical design, access, permissions and operations.','No fees, availability, ticketing, procurement, permits, guest records or safety/access approval is provided. Regional delivery outside Catalonia requires separate agreement.','Choices stay only on the page and clear on refresh or departure; this downloaded file remains on your device.'].join('\n');}
