import {writeFile,readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
export const routes=[['index.html','Home'],['projects.html','Projects'],['services.html','Services'],['delivery.html','Delivery'],['studio.html','Studio'],['brief.html','Start a brief']];
export const mark=`<svg viewBox="0 0 40 40" aria-hidden="true"><path d="M34 6H6v28h28V20H20" fill="none" stroke="currentColor" stroke-width="4"/></svg>`;
export const image=(name,alt,extra='')=>`<img src="assets/${name}.webp" srcset="assets/${name}-768.webp 768w,assets/${name}.webp 1536w" sizes="(max-width:700px) 100vw,80vw" width="1536" height="1024" alt="${alt}" ${extra}>`;
export const button=(href,text,variant='')=>`<a class="button ${variant}" href="${href}">${text}<span aria-hidden="true">↗</span></a>`;
export const intro=(label,title,text)=>`<div class="page-intro"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${text}</p></div>`;
export const cta=()=>`<section class="cta"><h2>What should happen<br>when people arrive?</h2>${button('brief.html','Start with a project brief')}</section>`;
const hash=createHash('sha256');for(const f of ['site.css','app.js','data.js','visuals.js'])hash.update(await readFile(new URL(f,import.meta.url)));const version=hash.digest('hex').slice(0,8);
export async function page(file,title,body){await writeFile(new URL(file,import.meta.url),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Gatherline Projects</title><meta name="description" content="Gatherline Projects is a fictional Barcelona studio for content-led temporary exhibitions, pop-ups and small gatherings."><meta name="theme-color" content="#e95a30"><link rel="icon" href="assets/favicon.svg"><link rel="preload" href="assets/fonts/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="site.css?v=${version}"><script type="module" src="app.js?v=${version}"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-inner"><a class="brand" href="index.html" aria-label="Gatherline Projects home">${mark}<span>Gatherline<small>PROJECTS</small></span></a><nav class="nav" aria-label="Main navigation">${routes.map(([href,label])=>`<a href="${href}"${file===href?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header><main id="main" tabindex="-1">${body}</main><footer class="footer"><div class="wrap"><div class="footer-main"><div><a class="brand" href="index.html">${mark}<span>Gatherline<small>PROJECTS</small></span></a><p>Content, space and the people between.<br>Barcelona · Established 2017</p></div><div><h2>Explore the studio</h2><nav class="footer-links" aria-label="Footer navigation"><a href="projects.html">Three spatial projects</a><a href="services.html">Our scope of work</a><a href="delivery.html">Delivery and ownership</a><a href="studio.html">Meet the studio</a></nav></div><div><h2>Begin with the visitor</h2><a class="text-link" href="brief.html">Prepare a project brief ↗</a><p>Example contact only:<br>studio@gatherline.example</p></div></div><div class="footer-meta"><p>Fictional studio / concept website. All projects, people and scenes are imagined. No real client, event, attendance or award is claimed. Local tools send nothing; choices disappear on refresh or departure. Diagrams are not for navigation, access assurance or life-safety planning.</p><a href="/#work" data-showcase>Return to Showcase ↗</a></div></div></footer></body></html>`,'utf8');}
