import {kits,blocks,readings,periods,regions,crops,connections,roles,csv} from './data.js';import {tableRows,plot} from './data-view.js';
document.querySelectorAll('[data-showcase]').forEach(link=>{if(!location.pathname.startsWith('/showcase/products/'))link.href='/showcase/#work'});
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const dataControls=document.getElementById('data-controls');
if(dataControls){
 const block=document.getElementById('block'),period=document.getElementById('period'),metric=document.getElementById('metric'),missingOnly=document.getElementById('missing-only'),output=document.getElementById('data-output'),inspection=document.getElementById('record-inspection'),status=document.getElementById('data-status'),exportButton=document.getElementById('download-data');let current=[];
 dataControls.disabled=false;
 function render(){
  const selectedBlock=blocks.find(b=>b.id===block.value);current=readings.filter(r=>r.block===block.value&&(period.value==='all'||period.value==='first'&&r.day<=7||period.value==='second'&&r.day>=8)&&(!missingOnly.checked||r.index===null||r.battery===null));const missing=current.filter(r=>r[metric.value]===null).length;
  inspection.hidden=true;inspection.innerHTML='';exportButton.disabled=current.length===0;
  output.innerHTML=`<dl class="data-summary"><div><dt>Block and node</dt><dd>Block ${block.value.toUpperCase()} / ${selectedBlock.node}</dd></div><div><dt>Displayed records</dt><dd>${current.length}</dd></div><div><dt>Missing values in measure</dt><dd>${missing}</dd></div></dl>${current.length?plot(current,metric.value)+`<p class="chart-note">${metric.value==='index'?'Synthetic moisture index / 0–100 demonstration scale':'Synthetic battery percentage / 0–100%'} / September day numbers. Short brown marks indicate a missing value.</p><div class="table-wrap" tabindex="0" role="region" aria-label="Daily record table"><table><thead><tr><th scope="col">Inspect date</th><th scope="col">Index</th><th scope="col">Battery</th><th scope="col">Record</th></tr></thead><tbody>${tableRows(current)}</tbody></table></div>`:'<div class="empty">No records match these choices. Clear the missing-value filter or choose another block or week.</div>'}`;
  output.querySelectorAll('[data-inspect]').forEach(button=>button.addEventListener('click',()=>{
   const row=current.find(r=>r.date===button.dataset.inspect);inspection.innerHTML=`<h3 id="inspection-title">${selectedBlock.name} · ${row.date}</h3><p><strong>Node:</strong> ${row.node} · <strong>Record:</strong> ${row.status}</p><p><strong>Synthetic moisture index:</strong> ${row.index??'Missing'} · <strong>Battery:</strong> ${row.battery===null?'Missing':row.battery+'%'}</p><p>${row.index===null?'The index was not received in this invented record. No substitute value or cause is inferred.':'This invented value is a record to inspect, not a crop threshold or instruction.'}</p>`;inspection.hidden=false;inspection.focus();status.textContent='Inspecting '+row.date+'. This is synthetic data.';
  }));status.textContent=current.length+' synthetic records displayed for '+selectedBlock.name+', '+periods[period.value]+'.';
 }
 function reset(){block.value='a';period.value='all';metric.value='index';missingOnly.checked=false;render()}
 [block,period,metric,missingOnly].forEach(control=>control.addEventListener('change',render));exportButton.addEventListener('click',()=>{if(!current.length)return;download(csv(current),'verdant-'+block.value+'-'+period.value+(missingOnly.checked?'-gaps':'')+'.csv','text/csv;charset=utf-8');status.textContent=current.length+' displayed rows downloaded. Nothing was sent.'});window.addEventListener('pageshow',event=>{if(event.persisted)reset()});reset();
}
const form=document.getElementById('enquiry-form');
if(form){
 const count=document.getElementById('block-count'),role=document.getElementById('role'),crop=document.getElementById('crop'),connection=document.getElementById('connection'),region=document.getElementById('region'),confirm=document.getElementById('local-confirm'),error=document.getElementById('enquiry-error'),result=document.getElementById('enquiry-result'),status=document.getElementById('enquiry-status');
 form.reset();document.getElementById('enquiry-fields').disabled=false;const query=new URLSearchParams(location.search),prefill={starter:'1',multi:'3',partner:'6'};if(query.get('kit') in prefill)count.value=prefill[query.get('kit')];if(location.search)history.replaceState(null,'',location.pathname+location.hash);
 form.addEventListener('reset',()=>{result.hidden=true;result.innerHTML='';form.hidden=false;error.hidden=true;status.textContent='Choices cleared. Nothing was sent or stored.'});window.addEventListener('pageshow',event=>{if(event.persisted)form.reset()});
 form.addEventListener('submit',event=>{
  event.preventDefault();const n=Number(count.value);let message='';
  if(!Number.isInteger(n)||n<1||n>12)message='Enter a whole number from 1 to 12 orchard blocks.';else if(!(role.value in roles))message='Choose your working role.';else if(!(crop.value in crops))message='Choose an orchard context.';else if(!(connection.value in connections))message='Choose the current connection position.';else if(!(region.value in regions))message='Choose a broad field area.';else if(!confirm.checked)message='Confirm the local scope and no-agronomic-recommendation boundary.';
  if(message){error.textContent=message;error.hidden=false;error.focus();return}
  error.hidden=true;const wide=n>6,noConnection=connection.value==='none',kit=wide?null:n===1?kits[0]:n<=3?kits[1]:kits[2];
  const title=wide?'Scope the wider field first.':noConnection?'Resolve the connection before a kit.':'A monitoring scope to discuss.';
  const connectionAction={checked:'A cellular signal has been observed in this scenario. Confirm the actual node-to-gateway path and a communications plan during field review; no continuous connection is promised.',intermittent:'Record the intermittent connection as an open issue. Agree a field communications check and how missing uploads would be followed up before treating the setup as ready.',unknown:'A communications check comes before a final kit scope. Gateway placement and the data route remain unconfirmed.',none:'No available connection is selected. Discuss a communications route or a separate bench demonstration first. No connected field deployment is proposed by this note.'}[connection.value];
  const regionAction=region.value==='local'?'The selected area fits our primary field region. Access, service availability and an actual visit still need separate agreement.':region.value==='outside'?'The selected area is outside our primary field region. Identify a local service arrangement before assuming on-site support from Verdant Row.':'Confirm the broad service area before discussing access or a field visit.';
  const roleAction=role.value==='partner'?'Partner handover: identify the grower decision owner, the partner reviewing context and the person maintaining node records. No professional appointment is created here.':'Grower handover: name the operating owner and the appropriate adviser who will interpret readings. The field team supports the record rather than replacing agronomic judgement.';
  const cropAction=crop.value==='other'?'The orchard crop is not one of the two example contexts. Confirm crop-specific monitoring questions with the appointed adviser before using a standard field plan.':`For the selected ${crops[crop.value].toLowerCase()}, record the block context with the adviser. This note specifies no depths, thresholds or irrigation schedule.`;
  const scopeAction=wide?'More than six blocks falls outside the three starting configurations. Define a smaller pilot or a separate multi-site scope; no hardware quantities or package price are proposed.':noConnection?`${kit.name} is a quantity reference for ${n} block${n===1?'':'s'} only. Connectivity must be resolved before a field configuration is proposed.`:`${kit.name} is a provisional starting configuration for ${n} block${n===1?'':'s'}. Field conditions can change placement and gateway requirements.`;
  const checks=wide?['Define the wider monitoring question and a manageable pilot.','Identify field-service and data-review responsibilities.','Resolve connection and region before specifying equipment.']:['Confirm the block-to-node register with the field owner.','Agree site-specific placement, power and communications checks.','Review the first received records and leave missing values visible.','Name the person following up equipment questions and the adviser interpreting context.'];
  result.innerHTML=`<span class="result-kicker">Local field preparation / Nothing sent</span><h2 id="result-title">${title}</h2><dl class="result-meta"><div><dt>Blocks</dt><dd>${n}</dd></div><div><dt>Role and orchard</dt><dd>${roles[role.value]} / ${crops[crop.value]}</dd></div><div><dt>Connection</dt><dd>${connections[connection.value]}</dd></div><div><dt>Field area</dt><dd>${regions[region.value]}</dd></div></dl><div class="boundary"><p>${scopeAction}</p></div>${kit?`<h3>${kit.name} / Quantity reference</h3><dl class="specs"><div><dt>Nodes</dt><dd>${kit.nodes}</dd></div><div><dt>Probes</dt><dd>${kit.nodes}</dd></div><div><dt>Initial gateways</dt><dd>${kit.gateways}</dd></div></dl>`:''}<h3>Connection comes first</h3><p>${connectionAction}</p><h3>Service and review owners</h3><p>${regionAction}</p><p>${roleAction}</p><p>${cropAction}</p><h3>Preparation checklist</h3><ol>${checks.map(c=>`<li>${c}</li>`).join('')}</ol><div class="boundary"><p>No kit order, price, appointment, live reading, irrigation action or agronomic advice is created. Actual scope, communications charges and seasonal support require separate agreement.</p></div><div class="buttons"><button class="button" data-download type="button">Download field note (TXT)</button><button class="button outline" data-edit type="button">Edit choices</button><button class="button outline" data-clear type="button">Clear and start again</button></div>`;
  form.hidden=true;result.hidden=false;status.textContent='Your field note was created locally. Nothing was sent.';result.focus();result.querySelector('[data-edit]').addEventListener('click',()=>{form.hidden=false;result.hidden=true;count.focus();status.textContent='Editing the field scope.'});result.querySelector('[data-clear]').addEventListener('click',()=>{form.reset();count.focus()});result.querySelector('[data-download]').addEventListener('click',()=>{
   const text=['VERDANT ROW - LOCAL FIELD NOTE','Fictional supplier; no kit order, agronomic advice or message.','',title,'Blocks: '+n,'Role: '+roles[role.value],'Orchard: '+crops[crop.value],'Connection: '+connections[connection.value],'Area: '+regions[region.value],'',scopeAction,kit?'Quantity reference: '+kit.nodes+' nodes, '+kit.nodes+' probes, '+kit.gateways+' initial gateways.':'No hardware quantity proposed.','','READINESS',connectionAction,regionAction,roleAction,cropAction,'','CHECKLIST',...checks.map((c,i)=>(i+1)+'. '+c),'','No physical location, personal data or operating record was collected. Nothing sent or booked.','Refresh or departure discards page choices. This file remains on your device.'].join('\n');download(text,'verdant-'+(kit?.id||'wider-scope')+'-field-note.txt','text/plain;charset=utf-8');status.textContent='The field note was downloaded to your device. Nothing was sent.';
  });
 });
}
