export const kits=[
{id:'starter',name:'Orchard Starter',blocks:'1 block',nodes:2,gateways:1,fit:'Start with one defined block and an owner who will review the readings.',description:'A small monitoring setup for a grower establishing a first field record.',included:['Two sensor nodes with two probe assemblies.','One gateway provision and a scoped placement plan.','An initial data-quality review and owner handover.'],handover:'A grower-facing record of node identities, locations to confirm and how missing readings will be followed up.'},
{id:'multi',name:'Multi-block Monitor',blocks:'2–3 blocks',nodes:6,gateways:1,fit:'Compare a small group of blocks while keeping each node and its context identifiable.',description:'A coordinated setup for a grower team reviewing more than one field context.',included:['Six sensor nodes with six probe assemblies.','One initial gateway provision, subject to range review.','A block register, initial data-quality review and owner handover.'],handover:'A block-to-node register and a shared review routine, with a clear owner for connectivity questions.'},
{id:'partner',name:'Partner Kit',blocks:'4–6 blocks',nodes:12,gateways:2,fit:'Organise a wider grower or agronomy-supported group with a named data-review owner.',description:'A structured monitoring scope for a partner team coordinating several orchard blocks.',included:['Twelve sensor nodes with twelve probe assemblies.','Two initial gateway provisions, subject to field review.','A partner setup discussion, data-quality review and handover materials.'],handover:'A common naming register, role-based review responsibilities and a handover session for the grower and partner.'}
];
export const blocks=[{id:'a',name:'Block A / West row',node:'A-01'},{id:'b',name:'Block B / Middle row',node:'B-01'},{id:'c',name:'Block C / East row',node:'C-01'}];
const values={a:[52,50,48,47,55,57,54,52,50,49,56,58,55,53],b:[61,59,57,55,null,62,60,58,56,54,52,59,57,55],c:[43,42,40,46,48,45,43,41,44,null,49,47,45,44]};
export const readings=blocks.flatMap((b,bi)=>values[b.id].map((index,i)=>({block:b.id,node:b.node,date:'2026-09-'+String(i+1).padStart(2,'0'),day:i+1,index,battery:b.id==='c'&&i===9?null:98-bi*7-i,status:index===null?(b.id==='b'?'Partial record':'Not received'):'Received'})));
export const periods={all:'1–14 September',first:'1–7 September',second:'8–14 September'};
export const regions={local:'Fresno, Madera, Kings or Tulare',outside:'Outside the primary field area',unknown:'Location not confirmed'};
export const crops={almond:'Almond orchard',pistachio:'Pistachio orchard',other:'Another orchard crop'};
export const connections={checked:'Cellular signal observed',intermittent:'Signal is intermittent',unknown:'Connection not checked',none:'No connection available'};
export const roles={grower:'Grower or operating team',partner:'Agronomy or field partner'};
export const backgroundSource='https://www.ucanr.edu/site/irrigation-and-nutrient-management/soil-moisture-sensors';
export const csv=(rows)=>['block,node,date,synthetic_moisture_index,battery_percent,record_status',...rows.map(r=>[r.block.toUpperCase(),r.node,r.date,r.index??'',r.battery??'',r.status].join(','))].join('\n')+'\n';
