import {writeFile,readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
export const routes=[['index.html','Home'],['kits.html','Kits'],['in-the-field.html','In the field'],['data-example.html','Data example'],['company.html','Company'],['enquiry.html','Plan a field enquiry']];
export const mark=`<svg viewBox="0 0 32 40" aria-hidden="true"><path d="M16 37V11M16 27C4 27 2 17 2 17c11-1 14 5 14 10M16 18C28 18 30 6 30 6 19 6 16 11 16 18M16 11C9 7 13 1 13 1c6 2 7 7 3 10" fill="none" stroke="currentColor" stroke-width="1.6"/></svg>`;
export const image=(name,alt,extra='')=>`<img src="assets/${name}.webp" srcset="assets/${name}-768.webp 768w,assets/${name}.webp 1536w" sizes="(max-width:700px) 100vw,75vw" width="1536" height="1024" alt="${alt}" ${extra}>`;
export const button=(href,text,variant='')=>`<a class="button ${variant}" href="${href}">${text}<span aria-hidden="true">↗</span></a>`;
export const intro=(label,title,text)=>`<div class="page-intro"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${text}</p></div>`;
export const cta=()=>`<section class="cta"><h2>Start with the block.<br>Then plan the monitoring.</h2>${button('enquiry.html','Prepare a field enquiry')}</section>`;
const version=createHash('sha256').update(await readFile(new URL('site.css',import.meta.url))).digest('hex').slice(0,8);
export async function page(file,title,body){await writeFile(new URL(file,import.meta.url),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Verdant Row</title><meta name="description" content="Orchard monitoring kits, field setup and data-review handovers from fictional Fresno supplier Verdant Row."><meta name="theme-color" content="#394d23"><link rel="icon" href="assets/favicon.svg"><link rel="preload" href="assets/fonts/source-serif.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="site.css?v=${version}"><script type="module" src="app.js?v=${version}"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-row"><a class="brand" href="index.html" aria-label="Verdant Row home">${mark}Verdant Row</a><nav class="nav" aria-label="Main navigation">${routes.map(([href,label])=>`<a href="${href}"${href===file?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header><main id="main" tabindex="-1">${body}</main><footer class="footer"><div class="wrap"><div class="footer-top"><div><a class="brand" href="index.html">${mark}Verdant Row</a><p>Field monitoring with a clear handover.<br>Fresno, California · Established 2019</p></div><div><h2>From block to record</h2><nav class="footer-links" aria-label="Footer navigation"><a href="kits.html">Three monitoring kits</a><a href="in-the-field.html">Field setup and ownership</a><a href="data-example.html">Read a finite data example</a></nav></div><div><h2>Begin with the field</h2><a class="text-link" href="enquiry.html">Prepare an enquiry ↗</a><p>Example contact only:<br>field@verdantrow.example</p></div></div><div class="footer-meta"><p>Fictional supplier / concept website. Images depict generated equipment, orchards and people. All readings are synthetic. No real hardware performance, agronomic advice, crop result or water saving is claimed. Local tools send nothing; choices disappear on refresh or departure.</p><a href="/#work" data-showcase>Return to Showcase ↗</a></div></div></footer></body></html>`,'utf8')}
