export const places = [
  {slug:'dock-court',name:'Dock Court',area:'Dockside',character:'Old brick. New working days.',description:'A retained four-storey brick block brings offices above small shops into one shared court. Separate retail entrances keep the daily rhythm of the ground floor distinct from the workplaces above.',alt:'Four-storey red-brick commercial courtyard with separate shopfronts, bicycles and planting',material:'Red brick / black-framed glazing',shared:'Central courtyard',arrival:'Retail units have their own ground-floor doors. Office arrivals use the shared stair entrance off the court. Confirm any step-free route and lift requirements during a real site review.',operations:'Keep the passage through the courtyard clear. Large deliveries would need to be coordinated around the shared route and individual shop entrances.',fit:'For a small office team looking for a defined layout, or a non-food shop prepared to plan its own interior.',question:'How will your visitors and deliveries use the same courtyard?',email:'dockcourt.operations@commonquay.example'},
  {slug:'linden-yard',name:'Linden Yard',area:'Garden Quarter',character:'A smaller scale, around a shared yard.',description:'Three storeys of yellow brick enclose a planted yard. The example office suits a smaller team; the ground-floor retail shell gives a shop or showroom space to establish its own layout.',alt:'Three-storey yellow-brick courtyard property with a planted shared yard and small shopfronts',material:'Yellow brick / planted ground',shared:'Planted yard and seating',arrival:'The shared yard leads to office access and individual ground-floor premises. Check the exact entrance, deliveries and any access needs before making a decision.',operations:'The yard is a shared place, not an extension of an individual shop. Outdoor displays, deliveries and alterations would need a separate conversation.',fit:'For a smaller office or a non-food retail business that values a quieter shared setting.',question:'What should stay inside your unit, and what needs shared-space agreement?',email:'lindenyard.operations@commonquay.example'},
  {slug:'platform-house',name:'Platform House',area:'Junction East',character:'A clear front door for a growing business.',description:'A five-storey pale-concrete and metal block opens onto a broad forecourt. Shared reception serves the offices, while the ground floor gives retail and showroom uses their own frontage.',alt:'Five-storey pale-concrete and charcoal-metal commercial building with reception and broad planted forecourt',material:'Pale concrete / charcoal metal',shared:'Reception and forecourt',arrival:'Office visitors arrive through the shared reception. The ground-floor sample retail unit has a separate front door. Visitor hours and access arrangements would be agreed with the operator.',operations:'Reception and the forecourt serve more than one occupier. Discuss visitor arrivals, larger deliveries and signage before finalising an operational plan.',fit:'For a larger office team comparing a fitted layout, or a showroom looking for an existing retail arrangement.',question:'How much visitor activity should your entrance and reception support?',email:'platformhouse.operations@commonquay.example'}
];
export const units = [
  {id:'D-204',slug:'d-204',place:'dock-court',use:'office',area:128,floor:'Second floor',fit:'fitted',rent:1920,zones:[['Workspace',88],['Meeting',18],['Support',22]],note:'A defined work zone and separate meeting area, with support space for circulation and storage. Review the existing layout against how your team works.'},
  {id:'D-01',slug:'d-01',place:'dock-court',use:'retail',area:84,floor:'Ground floor',fit:'shell',rent:1680,zones:[['Front',58],['Back',18],['Support',8]],note:'A ground-floor retail shell with a front-of-house zone and a smaller back area. Internal fit-out, service requirements and signage need to be scoped.'},
  {id:'L-102',slug:'l-102',place:'linden-yard',use:'office',area:76,floor:'First floor',fit:'part-fitted',rent:1064,zones:[['Workspace',50],['Meeting',14],['Support',12]],note:'A smaller office with an existing meeting partition. The remaining finishes and layout preparation would be agreed before any occupation.'},
  {id:'L-01',slug:'l-01',place:'linden-yard',use:'retail',area:112,floor:'Ground floor',fit:'shell',rent:1904,zones:[['Front',82],['Back',22],['Support',8]],note:'A wider front-of-house zone with back-of-house space. A non-food shop or showroom would need a defined fit-out brief before terms could be discussed.'},
  {id:'P-301',slug:'p-301',place:'platform-house',use:'office',area:210,floor:'Third floor',fit:'fitted',rent:3150,zones:[['Workspace',140],['Meetings',40],['Support',30]],note:'The largest office in this collection combines a working area with meeting space. Check the layout and visitor pattern rather than inferring a desk capacity from area.'},
  {id:'P-02',slug:'p-02',place:'platform-house',use:'retail',area:96,floor:'Ground floor',fit:'fitted',rent:2016,zones:[['Front',70],['Stock',18],['Support',8]],note:'An existing retail layout separates the display area from stock and support space. The sample fit-out does not include furniture or stock.'}
];
export const fitLabels = {'fitted':'Fitted','part-fitted':'Part-fitted','shell':'Shell'};
export const fitNotes = {'fitted':'Defined layout, lighting and internal finishes. Furniture is not included.','part-fitted':'Existing partitions with further preparation and finishes to agree.','shell':'Internal fit-out still needs to be scoped and agreed.'};
export const money = amount => new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(amount);
export const rentNote = 'Illustrative base rent per month. Excludes charges, utilities, tax and fit-out; these extras are not estimated. Fictional availability, not a letting offer.';
