document.documentElement.classList.add('js');
const menu=document.querySelector('.menu'),navigation=document.querySelector('#navigation');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));navigation.dataset.open=String(open);});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){menu.setAttribute('aria-expanded','false');navigation.dataset.open='false';menu.focus();}});
if(!location.pathname.startsWith('/showcase/products/'))document.querySelector('.showcase-return').href='/showcase/#work';

const form=document.querySelector('#scope-form');
if(form){
 const services=JSON.parse(document.querySelector('#service-data').textContent);
 const result=document.querySelector('#scope-result'),error=document.querySelector('#scope-error');
 form.querySelector('[type="submit"]').disabled=false;
 const preset=new URLSearchParams(location.search).get('situation');if(services.some(service=>service.id===preset))form.elements.situation.value=preset;
 let downloadText='',downloadName='stonepath-scope-checklist.txt';
 const list=items=>`<ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
 const groupLabels={below:'Fewer than 50 people',small:'50–149 people',medium:'150–500 people',above:'More than 500 people'};
 const footprints={one:'one site',several:'two to four sites',complex:'five or more sites'};
 const itOwners={internal:'Internal IT team',provider:'External IT provider',shared:'Internal team and provider'};
 const materialLabels={ready:'Available for scoped preparation',partial:'Some exist, some are missing',none:'Not gathered yet'};
 const participantNotes={internal:'Invite the internal IT owner and a business sponsor able to agree scope and follow-up responsibilities.',provider:'Invite the IT-provider representative and an internal business owner who can authorise decisions. Do not leave business ownership solely with the provider.',shared:'Bring both the internal IT owner and the provider representative. Make the handover between them an explicit topic.'};
 const roleNotes={review:'Include the people who own the three proposed business systems and process notes. The starting scope allows up to five stakeholder interviews.',tabletop:'Choose up to eight decision-making participants, including operations and communications roles relevant to the scenario.',suppliers:'Include procurement or contract owners and the business process owners for up to five chosen suppliers.'};
 const finish=(title,body,active=false)=>{result.innerHTML=`<span class="result-label">${active?'Service boundary':'Local scope preparation'}</span><h2 id="result-heading" tabindex="-1">${title}</h2>${body}<p class="boundary">Nothing has been sent or booked. This is a local preparation record, not a quote, suitability assessment or assurance opinion. Choices clear on refresh or departure; downloaded files remain on your device.</p><div class="actions"><button type="button" class="button" data-action="download">${active?'Download boundary note (TXT)':'Download checklist (TXT)'}</button><button type="button" class="plain" data-action="edit">Edit choices</button><button type="button" class="plain" data-action="clear">Clear checklist</button></div>`;form.hidden=true;result.hidden=false;document.querySelector('#result-heading').focus();};
 form.addEventListener('submit',event=>{
  event.preventDefault();const missing=[...form.querySelectorAll('select')].find(select=>!select.value);
  if(missing){error.hidden=false;error.textContent='Choose all six answers to prepare the right scope and boundaries.';missing.focus();return;}error.hidden=true;
  const answers=Object.fromEntries(new FormData(form));const service=services.find(item=>item.id===answers.situation);if(!service)return;
  const context=`${groupLabels[answers.employees]} · ${footprints[answers.footprint]} · ${itOwners[answers.ownership]}`;
  if(answers.timing==='active'){
   const note='Stonepath offers planned advisory work. This website does not provide incident response, monitoring or an emergency reporting channel. Follow your organisation\'s existing incident arrangements and designated response provider.';
   downloadName='stonepath-service-boundary.txt';downloadText=['STONEPATH SECURITY / SERVICE BOUNDARY','Fictional company / concept website','Active disruption is outside these services.',`Selected interest: ${service.name}`,`Context: ${context}`,note,'No scope enquiry, incident report or appointment has been created.'].join('\r\n\r\n');
   finish('An active disruption needs a different channel.',`<p>${note}</p><div class="gap"><h3>No engagement request created</h3><p>Your selected interest was ${service.name}. Return to this preparation tool for planned advisory work once that is the appropriate context.</p></div><p class="result-context">${context}</p>`,true);return;
  }
  const gaps=[];
  if(answers.employees==='below'||answers.employees==='above')gaps.push('Your employee range is outside our usual 50–500-person focus. Confirm whether a smaller or differently staffed advisory engagement is appropriate before assuming a standard scope.');
  if(answers.footprint==='complex')gaps.push('Five or more sites need a separate boundary discussion. Select a representative entity, systems or supplier group before agreeing effort.');
  if(answers.materials==='partial')gaps.push('List which relevant process notes exist and which are missing. Agree how missing context will be recorded; do not assume it has been reviewed.');
  if(answers.materials==='none')gaps.push('Nominate a coordinator to gather a high-level document inventory. Identify owners before sharing any material; do not upload records to this website.');
  const rangeNeeded=['below','above'].includes(answers.employees)||answers.footprint==='complex';
  const title=rangeNeeded?'A scope conversation comes first.':gaps.length?'Prepare the missing context.':`${service.name}: a useful starting point.`;
  const timingNote=rangeNeeded?'The published service is a reference point, not a confirmed fit. Effort and scope need to be agreed.':`Starting working shape: ${service.time}. Confirm availability and the written fixed-fee scope separately.`;
  const prep=[...service.prepare,answers.materials==='ready'?'Confirm which versions of the available materials belong in the agreed evidence set and who can authorise their use.':answers.materials==='partial'?'Make a short list of present and missing materials so the scope can reflect the gaps.':'Gather a high-level inventory and identify the owner of each relevant process note.',answers.footprint==='one'?'Confirm the single-site operating context and the business roles affected by the chosen scope.':answers.footprint==='several'?'Choose representatives from the two-to-four-site footprint and note where the same process is handled differently.':'Choose a representative starting boundary for the five-plus-site footprint before a fee or effort is agreed.'];
  const participants=[participantNotes[answers.ownership],roleNotes[service.id],answers.employees==='medium'?'For 150–500 people, agree which departments need representation while staying inside the service participant limit.':answers.employees==='small'?'For 50–149 people, identify a coordinator who can connect the IT and business roles without adding unnecessary attendees.':'Discuss an appropriate participant model for the selected employee range before confirming the engagement.'];
  downloadName='stonepath-scope-checklist.txt';downloadText=['STONEPATH SECURITY / LOCAL SCOPE CHECKLIST','Fictional company / concept website',title,`Selected service: ${service.name}`,`Context: ${context}`,`Material readiness: ${materialLabels[answers.materials]}`,timingNote,`Starting scope: ${service.scope}`,'PARTICIPANTS',...participants.map(item=>`- ${item}`),'PREPARATION',...prep.map(item=>`- ${item}`),'DELIVERABLES',...service.outputs.map(item=>`- ${item}`),'QUESTIONS TO RESOLVE',...(gaps.length?gaps:['Confirm the starting boundary, participant roles and evidence-handling agreement.']).map(item=>`- ${item}`),`BOUNDARY: ${service.boundary}`,'Nothing sent or booked. Not a quote, suitability assessment or assurance opinion. Current-page state clears on refresh; this downloaded file remains on your device.'].join('\r\n\r\n');
  finish(title,`<p>${timingNote}</p><p class="result-context"><strong>${service.name}</strong><br>${context}<br>${service.scope}</p>${gaps.length?`<div class="gap"><h3>Questions to resolve before scoping</h3>${list(gaps)}</div>`:''}<h3>People to involve</h3>${list(participants)}<h3>Bring to preparation</h3>${list(prep)}<h3>The deliverables to discuss</h3>${list(service.outputs)}<div class="notice" style="margin-top:25px"><strong>Boundary:</strong> ${service.boundary}</div>`);
 });
 form.addEventListener('reset',()=>{form.hidden=false;result.hidden=true;error.hidden=true;downloadText='';});
 result.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='edit'){form.hidden=false;result.hidden=true;form.elements.situation.focus();}if(action==='clear'){form.reset();form.elements.situation.focus();}if(action==='download'){const url=URL.createObjectURL(new Blob([downloadText],{type:'text/plain;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=downloadName;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
}
