export const services=[
 {id:'review',name:'First Review',question:'Where should we start?',line:'A clear starting point for the work ahead.',description:'Bring the people, process notes and system context together. We turn a defined evidence set into an action register your team can discuss and own.',time:'5 consulting days across 2 weeks',scope:'1 legal entity · up to 3 named systems · up to 5 stakeholder interviews',prepare:['A high-level list of the three systems in scope.','Current access, handover and interruption process notes.','The people who own IT delivery and business decisions.'],outputs:['A prioritised action register with evidence notes.','Named ownership questions and a practical readout.','An explicit record of what was not reviewed.'],boundary:'No penetration testing, asset-wide scanning, certification or continuous monitoring.'},
 {id:'tabletop',name:'Tabletop Day',question:'Who decides when work is interrupted?',line:'Rehearse the decisions before the disruption.',description:'Work through one agreed interruption scenario in a facilitated room. Pause at the decision points, clarify who is involved and record the follow-up work.',time:'1 workshop day, with preparation and readout across 2 weeks',scope:'1 fictional scenario · up to 8 participants',prepare:['A current interruption or incident plan, if you have one.','A list of decision-making roles and alternate contacts.','An agreed operational scenario and workshop participants.'],outputs:['An agreed scenario pack and decision log.','Observations on roles, communications and handovers.','An action note with proposed follow-up owners.'],boundary:'No live attack, production recovery exercise, system changes or active incident response.'},
 {id:'suppliers',name:'Supplier Map',question:'What do we depend on?',line:'See the business behind the supplier list.',description:'Connect a small set of business-critical suppliers to the processes they support. Separate what is known from the questions that still need an owner.',time:'3 consulting days across 2 weeks',scope:'1 legal entity · up to 5 named business-critical suppliers',prepare:['A list of the five suppliers to discuss and their contract owners.','The business processes that rely on each supplier.','Existing supplier documents or answers, without confidential details.'],outputs:['A readable business-dependency map.','An evidence-request list with unanswered questions.','A supplier follow-up register with owner roles.'],boundary:'No supplier audit, assurance rating or verification of every supplier assertion.'}
];
export const observations=[
 {id:'R01',title:'Name the final handover verifier.',window:'First 30 days',area:'Access handover',evidence:'The synthetic joiner/mover/leaver checklist names an internal requestor and an IT-provider implementer, but no role verifies that the handover is complete.',question:'Who confirms that the requested change matches the completed change, and where is that confirmation recorded?',action:'Agree a final verifier role with the IT provider. Add a completion check to the handover record and try it on an anonymised example.',owner:'Internal IT manager, with the IT provider',unknown:'No user account or live access record was inspected. The review does not establish whether any access is inappropriate.'},
 {id:'R02',title:'Put alternate decisions in the plan.',window:'Days 31–60',area:'Interruption readiness',evidence:'The sample interruption contact sheet names operational roles, but does not say who can take the decision when the primary role-holder is unavailable.',question:'If a primary decision owner cannot be reached, who has the authority and context to act?',action:'Agree alternate decision owners for the chosen interruption scenario. Use a short discussion exercise to check the contact and escalation sequence.',owner:'Operations lead, supported by internal IT',unknown:'No response exercise or recovery test took place. The document review cannot establish how people would act during a real interruption.'},
 {id:'R03',title:'Connect suppliers to the work.',window:'Days 61–90',area:'Supplier context',evidence:'The illustrative supplier register lists contract owners but does not identify the business process depending on each named supplier.',question:'Which day-to-day activity would need a different arrangement if this supplier was unavailable?',action:'Add the supported business process and its owner for up to five chosen suppliers. Record unanswered dependency questions for follow-up.',owner:'Procurement lead, with business process owners',unknown:'No supplier was contacted or audited. The sample evidence does not establish a supplier control standard or assurance rating.'}
];
