export const services = [
  {id:'pilot',name:'Pilot Plate',stage:'A question to explore',intro:'A small feasibility study around one plate-based research readout.',inputs:['The research question and the decision it should inform','A description of the material and the proposed readout','Any existing observations, including what did not work'],deliverables:['A scoped feasibility note','Labelled raw output and a calculation sheet','An open-questions register for the next discussion'],boundary:'A feasibility study can expose a limitation. It does not promise a working assay, a biological conclusion or a validated method.'},
  {id:'transfer',name:'Transfer Review',stage:'A method to hand over',intro:'A documented comparison between the method you have and the handover you need.',inputs:['The current written method and its version','Instrument settings and the calculation convention','A labelled example output with known limitations'],deliverables:['A source-to-receiving-method comparison','A record of missing settings and assumptions','A proposed discussion sequence before any lab work'],boundary:'A document review is not proof that two instruments or laboratories produce equivalent results. Any further work needs a separately agreed scope.'},
  {id:'batch',name:'Research Batch',stage:'A defined readout to repeat',intro:'A bounded set of research items, run against a method already agreed for the project.',inputs:['The agreed method and calculation version','A coded item manifest with no personal information','The reporting structure and exception rules'],deliverables:['A labelled run record and raw values','A calculation sheet linked to the source records','An exception register and project handover note'],boundary:'Repeated readings do not establish clinical meaning, product performance or regulatory suitability. Exceptions remain visible in the handover.'}
];
export const records = [
  {id:'BLK',group:'blank',label:'Background illustration',values:[48,50,52]},
  {id:'REF',group:'reference',label:'Reference illustration',values:[480,500,520]},
  {id:'A01',group:'a',label:'Series A / item 1',values:[148,150,152]},
  {id:'A02',group:'a',label:'Series A / item 2',values:[245,250,255]},
  {id:'A03',group:'a',label:'Series A / item 3',values:[340,350,360]},
  {id:'B01',group:'b',label:'Series B / item 1',values:[430,450,470]},
  {id:'B02',group:'b',label:'Series B / item 2',values:[530,550,570]},
  {id:'B03',group:'b',label:'Series B / item 3',values:[620,650,680]}
];
export const mean = values => values.reduce((sum,value)=>sum+value,0)/values.length;
export const studies = [
  {id:'HW-P07',service:'pilot',title:'Making the background visible.',question:'Could a first plate distinguish the proposed research signal from its buffer background?',inputs:'A non-clinical buffer description, a proposed readout and a short set of prior observations.',work:'The project was scoped around the measurement question and the records needed to revisit it. A labelled example output made the background contribution visible beside the individual readings.',handover:'Feasibility note, raw-value file, calculation sheet and a list of assumptions to revisit.',limit:'The study refined the question. It did not prove target binding, establish a concentration or validate a method.'},
  {id:'HW-T12',service:'transfer',title:'Finding the missing setting.',question:'What was missing between a written plate method and the receiving team\'s example output?',inputs:'A source method, two instrument-setting summaries and an illustrative calculation workbook.',work:'A line-by-line handover comparison identified an undocumented calculation convention. That convention remained an open item rather than being silently guessed.',handover:'Method comparison, version list and unresolved-setting register.',limit:'No claim of method equivalence was made. A further agreed study would be needed before any such conclusion.'},
  {id:'HW-R04',service:'batch',title:'Keeping the exception in the record.',question:'How should a small repeat-readout project preserve an unusual record during handover?',inputs:'An agreed research method, coded item list and the intended report structure.',work:'The handover linked each record to its raw values and calculation version. One record was retained with an explicit note, so the receiving team could see both the value and the question around it.',handover:'Run record, traceable raw file, calculation notes and exception register.',limit:'The record was not silently removed or labelled clinically meaningful. The example demonstrates reporting decisions, not a biological finding.'}
];
