import {cashRows,money,services} from './data.js';
const $=s=>document.querySelector(s);
const menu=$('.menu'),nav=$('#navigation');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open');menu.focus();}});
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
if($('#period')){
  const selected=()=>cashRows.filter(r=>$('#period').value==='h1'||r.quarter===$('#period').value);
  const render=()=>{const data=selected(),sum=key=>data.reduce((a,r)=>a+r[key],0);$('#cash-rows').innerHTML=data.map(r=>`<tr><th scope="row"><button type="button" data-month="${r.month}" aria-label="Inspect ${r.month}">${r.month}</button></th><td>${money(r.receipts)}</td><td>${money(r.outgoings)}</td><td>${money(r.net)}</td><td>${money(r.closing)}</td></tr>`).join('');$('#report-totals').innerHTML=[['Opening cash',data[0].opening],['Receipts',sum('receipts')],['Outgoings',sum('outgoings')],['Closing cash',data.at(-1).closing]].map(([label,value])=>`<div><span>${label}</span><strong>${money(value)}</strong></div>`).join('');$('#report-caption').textContent=`${data[0].month}–${data.at(-1).month} 2026 · ${data.length} synthetic records · EUR`;$('#trace').innerHTML='<h3>Read a month from left to right.</h3><p>Net movement = receipts − outgoings.<br>Closing cash = opening cash + net movement.</p>';};
  $('#period').addEventListener('change',render);$('#cash-rows').addEventListener('click',e=>{const btn=e.target.closest('[data-month]');if(!btn)return;const r=selected().find(item=>item.month===btn.dataset.month);if(r)$('#trace').innerHTML=`<h3>${r.month} 2026 · synthetic record</h3><p>Net: ${money(r.receipts)} − ${money(r.outgoings)} = ${money(r.net)}<br>Closing: ${money(r.opening)} + ${money(r.net)} = ${money(r.closing)}</p>`;});$('#csv').addEventListener('click',()=>download('ledgerwell-'+$('#period').value+'-synthetic.csv','dataset,month,opening_eur,receipts_eur,outgoings_eur,net_eur,closing_eur\n'+selected().map(r=>`LW-DEMO-01_SYNTHETIC,${r.month},${r.opening},${r.receipts},${r.outgoings},${r.net},${r.closing}`).join('\n')+'\n','text/csv'));
  window.addEventListener('pageshow',()=>{$('#period').value='h1';render();});
}
if($('#fit-form')){
  const form=$('#fit-form'),result=$('#fit-result');let outline='';form.hidden=false;
  const invalidate=()=>{result.hidden=true;outline='';$('#form-error').textContent='';};
  const reset=()=>{form.reset();invalidate();};
  form.addEventListener('input',invalidate);form.addEventListener('change',invalidate);
  const url=new URL(location.href),preset=url.searchParams.get('service');if(services.some(s=>s.id===preset))$('#service').value=preset;history.replaceState(null,'',location.pathname+location.hash);
  form.addEventListener('submit',e=>{e.preventDefault();invalidate();const value=id=>$('#'+id).value,fail=(id,message)=>{$('#form-error').textContent=message;$('#'+id).focus();};
    if(!services.some(s=>s.id===value('service')))return fail('service','Choose a service.');
    const volume=Number(value('volume')),months=Number(value('months'));if(!value('volume')||!Number.isInteger(volume)||volume<1||volume>5000)return fail('volume','Enter a whole monthly transaction count from 1 to 5000.');
    if(!['ready','gaps','mixed'].includes(value('records')))return fail('records','Choose the state of the records.');
    if(value('months')===''||!Number.isInteger(months)||months<0||months>12)return fail('months','Enter whole catch-up months from 0 to 12.');
    if(!['appointed','needed'].includes(value('adviser')))return fail('adviser','Choose the statutory adviser position.');
    if(!['preparation','filing'].includes(value('request')))return fail('request','Choose the main request.');
    if(!$('#ack').checked)return fail('ack','Acknowledge the local demonstration.');
    const s=services.find(item=>item.id===value('service')),outside=value('request')==='filing',questions=[`${volume} monthly transactions: ${volume>500?'discuss workload and record categories before agreeing a rhythm.':'confirm the mix of sales, purchases and other movements.'}`,value('records')==='ready'?'Confirm a complete starting period and the route for a future secure handover.':value('records')==='gaps'?'Make a missing-record inventory before setting preparation milestones.':'Agree a single record index for mixed paper and digital sources.',months?`Plan a staged starting point for ${months} catch-up months before the regular rhythm.`:'Confirm the first regular period; no catch-up months selected.',value('adviser')==='needed'?'Identify a separately appointed statutory adviser and confirm who owns any filing.':'Agree the handover format with your appointed statutory adviser.'];
    if(s.id==='quarterly')questions.push('Agree reporting categories and the owner questions for the quarterly discussion.');if(s.id==='yearend')questions.push('Request the statutory adviser’s records list and reconcile it against the available files.');if(s.id==='monthly')questions.push('Choose a monthly handover day and one owner for the open-items list.');
    $('#fit-status').textContent=outside?'Filing-only work is outside this scope.':'A starting checklist, ready to review.';$('#selected-service').textContent=s.name;$('#fit-output').textContent=outside?'No preparation engagement is proposed for a filing-only request. Speak with a separately appointed adviser about statutory work.':s.output;$('#fit-questions').replaceChildren(...questions.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));
    outline=`LEDGERWELL ACCOUNTS / FICTIONAL DEMO\n${$('#fit-status').textContent}\nService: ${s.name}\nMonthly transactions: ${volume}\nCatch-up months: ${months}\nRecords: ${$('#records option:checked').textContent}\nStatutory adviser: ${$('#adviser option:checked').textContent}\nMain request: ${$('#request option:checked').textContent}\n\nOutput: ${$('#fit-output').textContent}\n\nQuestions\n${questions.map(q=>'- '+q).join('\n')}\n\nNo engagement, financial advice, filing, mail or booking. Nothing sent or saved. Choices only exist on the current page and reset on reload/navigation.\n`;result.hidden=false;result.focus();
  });
  $('#fit-download').addEventListener('click',()=>{if(outline)download('ledgerwell-service-checklist.txt',outline);});$('#fit-edit').addEventListener('click',()=>{invalidate();$('#service').focus();});$('#fit-clear').addEventListener('click',()=>{reset();$('#service').focus();});window.addEventListener('pagehide',reset);window.addEventListener('pageshow',e=>{if(e.persisted)reset();});
}
