import {objects,currency,compareSize} from './objects.js';
const byId=id=>document.getElementById(id);
const query=new URLSearchParams(location.search);
const whole=(value,min,max)=>Number.isInteger(value)&&value>=min&&value<=max;
const dimensionsValid=values=>whole(values[0],1,500)&&whole(values[1],1,500)&&whole(values[2],1,100);
function resultText(result){return result.rows.map(r=>`${r.label}: ${r.value} mm; comparison ${r.min}–${r.max} mm. ${r.ok?'Within range.':r.value>r.max?`${r.value-r.max} mm over the maximum.`:`${r.min-r.value} mm below the minimum.`}`);}
const fitForm=byId('fit-form');
if(fitForm){
 const example={'arc-stand':[320,220,18],'dock-tray':[140,60,15],'fold-pouch':[180,90,25]};
 function resetExample(){const id=byId('fit-object').value;['width','depth','thickness'].forEach((axis,i)=>byId('fit-'+axis).value=String(example[id][i]));byId('measurement-help').textContent=id==='arc-stand'?'Measure the closed laptop, not its screen diagonal.':'Measure one stored item along the interior axes, including any protruding parts.';byId('fit-error').textContent='';byId('fit-result').innerHTML='<p class="kicker">Measurements changed</p><h2>Ready to compare.</h2><p>Review the example values, replace them with your item’s dimensions and compare again.</p>';}
 if(objects.some(p=>p.id===query.get('item')))byId('fit-object').value=query.get('item');
 resetExample();byId('fit-object').addEventListener('change',resetExample);
 fitForm.addEventListener('input',()=>{byId('fit-result').innerHTML='<p class="kicker">Measurements changed</p><h2>Compare again.</h2><p>The previous result no longer applies. Use the current values to make a new comparison.</p>';byId('fit-error').textContent='';});
 fitForm.addEventListener('submit',event=>{event.preventDefault();const id=byId('fit-object').value,values=['width','depth','thickness'].map(axis=>Number(byId('fit-'+axis).value));if(!dimensionsValid(values)||!example[id]){byId('fit-error').textContent='Use whole millimetres within the stated input ranges.';return;}const p=objects.find(p=>p.id===id),r=compareSize(id,...values);const params=new URLSearchParams({item:id,fit:id,w:String(values[0]),d:String(values[1]),t:String(values[2])});byId('fit-result').innerHTML=`<p class="kicker">${p.short} / dimensional comparison</p><h2>${r.ok?'Within the illustrated range.':'Size needs attention.'}</h2><ul class="fit-lines">${r.rows.map((row,i)=>`<li class="${row.ok?'within':'outside'}"><span>${row.ok?'Within range':'Size gap'}</span><p>${resultText(r)[i]}</p></li>`).join('')}</ul><p>${r.note}</p><a class="primary" href="desk-set.html?${params}">${r.ok?'Continue with these dimensions':'Keep this size gap in a set note'} ↗</a>`;byId('fit-result').focus();});
}
const setForm=byId('set-form');
if(setForm){
 let note='';
 const carriedId=query.get('fit'),carriedValues=['w','d','t'].map(k=>Number(query.get(k)));
 let hasCarried=objects.some(o=>o.id===carriedId)&&dimensionsValid(carriedValues);
 function read(){const lines=objects.map(p=>({p,qty:Number(byId(p.id+'-qty').value),finish:p.finishes.find(f=>f.id===byId(p.id+'-finish').value)}));const device=['width','depth','thickness'].map(axis=>Number(byId('device-'+axis).value));const desk=[Number(byId('desk-width').value),Number(byId('desk-depth').value)];return{lines,device,desk};}
 function valid(s){return s.lines.every(l=>whole(l.qty,0,4)&&l.finish)&&whole(s.desk[0],200,2500)&&whole(s.desk[1],150,1500)&&(!s.lines[0].qty||dimensionsValid(s.device));}
 function calculate(s){const selected=s.lines.filter(l=>l.qty>0);let width=40,depth=0,count=0,total=0,weight=0;const parts=[];for(const l of selected){const w=l.p.id==='arc-stand'?Math.max(l.p.width,s.device[0]):l.p.width,d=l.p.id==='arc-stand'?Math.max(l.p.depth,s.device[1]):l.p.depth;for(let i=0;i<l.qty;i++)parts.push({label:l.p.short,width:w,depth:d,colour:l.finish.colour});width+=w*l.qty;depth=Math.max(depth,d);count+=l.qty;total+=l.finish.price*l.qty;weight+=l.p.weight*l.qty;}width+=Math.max(0,count-1)*30;depth+=40;
  const notes=[];if(count){if(width>s.desk[0]||depth>s.desk[1])notes.push(`Desk space gap: this ${width} × ${depth} mm row exceeds the available ${s.desk[0]} × ${s.desk[1]} mm.${width>s.desk[0]?' Width needs '+(width-s.desk[0])+' mm more.':''}${depth>s.desk[1]?' Depth needs '+(depth-s.desk[1])+' mm more.':''}`);else notes.push(`Within the entered desk space by dimensions: ${s.desk[0]-width} mm spare width and ${s.desk[1]-depth} mm spare depth. This is not a stability or device-fit approval.`);}
  if(s.lines[0].qty){const fit=compareSize('arc-stand',...s.device);notes.push(`Arc device comparison: ${fit.ok?'within the illustrated range':'size gap remains'}. `+resultText(fit).join(' '));}
  if(hasCarried&&carriedId!=='arc-stand'&&selected.some(l=>l.p.id===carriedId)){const p=objects.find(o=>o.id===carriedId),r=compareSize(carriedId,...carriedValues);notes.push(`Carried ${p.short} item check: ${carriedValues.join(' × ')} mm; ${r.ok?'within dimensional allowance':'size gap remains'}. `+resultText(r).join(' '));}
  notes.push('One row, all selected quantities, 30 mm gaps and 20 mm outer edges. Leave additional room for actual cables, use and device movement.');notes.push('Non-powered concept objects. No electrical function or verified load, impact, heat-management or compatibility claim.');return{selected,width:count?width:0,depth:count?depth:0,count,total,weight,parts,notes};}
 function draw(r){const box=byId('layout-study');if(!r.count){box.innerHTML='<p>Choose a quantity to see the space it needs.</p>';return;}const scale=450/Math.max(r.width,450);let x=20*scale;box.innerHTML=`<svg viewBox="0 0 450 170" role="img" aria-label="Single-row arrangement: ${r.width} by ${r.depth} millimetres"><rect x="1" y="8" width="448" height="130" rx="5" fill="#f3f5f6" stroke="#7d8994"/>${r.parts.map(p=>{const rect=`<rect x="${x}" y="${20+(100-p.depth/Math.max(...r.parts.map(part=>part.depth))*100)/2}" width="${p.width*scale}" height="${p.depth/Math.max(...r.parts.map(part=>part.depth))*100}" rx="5" fill="${p.colour}" stroke="#17202b"/>`;x+=(p.width+30)*scale;return rect;}).join('')}<text x="225" y="163" text-anchor="middle" font-family="sans-serif" font-size="15" fill="#17202b">${r.width} × ${r.depth} mm row</text></svg><p class="micro">Plan view · selected finish colours · illustrative proportions</p>`;}
 function sync(){const s=read(),arc=Boolean(s.lines[0].qty);byId('device-fields').hidden=!arc;for(const axis of ['width','depth','thickness']){byId('device-'+axis).disabled=!arc;byId('device-'+axis).required=arc;}byId('set-error').textContent='';if(!valid(s)){byId('preview-total').textContent='Check the input values.';byId('layout-notes').textContent='Quantities and measurements must use whole numbers within their stated ranges.';byId('layout-study').replaceChildren();return;}const r=calculate(s);byId('preview-total').textContent=r.count?currency(r.total):'No objects yet.';draw(r);byId('layout-notes').replaceChildren();for(const text of r.count?r.notes:[]){const p=document.createElement('p');p.textContent=text;if(/gap:|gap remains/.test(text))p.className='size-gap';byId('layout-notes').append(p);}}
 if(objects.some(p=>p.id===query.get('item')))byId(query.get('item')+'-qty').value='1';
 if(hasCarried&&carriedId==='arc-stand')['width','depth','thickness'].forEach((axis,i)=>byId('device-'+axis).value=String(carriedValues[i]));
 setForm.addEventListener('input',sync);setForm.addEventListener('change',sync);
 setForm.addEventListener('submit',event=>{event.preventDefault();const s=read();if(!valid(s)){byId('set-error').textContent='Check whole-number quantities, finishes and measurements.';return;}const r=calculate(s);if(!r.count){byId('set-error').textContent='Choose at least one object before reviewing the set.';byId('arc-stand-qty').focus();return;}byId('set-result-lines').innerHTML=`<ul class="set-lines">${r.selected.map(l=>`<li><div><strong>${l.qty} × ${l.p.name}</strong><p>${l.finish.name} · ${currency(l.finish.price)} each · ${l.p.weight} g each</p></div><span>${currency(l.qty*l.finish.price)}</span></li>`).join('')}</ul><div class="set-total"><span>Illustrative total</span><span>${currency(r.total)}</span></div><p>${r.weight} g · ${r.width} × ${r.depth} mm single row</p>`;byId('set-result-notes').innerHTML='<h3>Keep these details with the set.</h3>';for(const text of r.notes){const p=document.createElement('p');p.textContent=text;byId('set-result-notes').append(p);}note=['LATCHLINE OBJECTS - LOCAL SET NOTE','Fictional company and concept objects; this is not an order.','',...r.selected.map(l=>`${l.qty} x ${l.p.name} / ${l.finish.name}: ${currency(l.qty*l.finish.price)}`),'',`Illustrative total: ${currency(r.total)}`,`Object weight: ${r.weight} g`,`Single row: ${r.width} x ${r.depth} mm`,`Available desk: ${s.desk[0]} x ${s.desk[1]} mm`,'',...r.notes,'','No checkout, payment, stock reservation, shipping or external message. Current-page demonstration.'].join('\n');setForm.hidden=true;byId('set-result').hidden=false;byId('set-result').focus();});
 byId('edit-set').addEventListener('click',()=>{setForm.hidden=false;byId('set-result').hidden=true;note='';byId('arc-stand-qty').focus();});
 byId('clear-set').addEventListener('click',()=>{setForm.reset();hasCarried=false;setForm.hidden=false;byId('set-result').hidden=true;note='';sync();byId('arc-stand-qty').focus();});
 byId('download-set').addEventListener('click',()=>{if(!note)return;const url=URL.createObjectURL(new Blob([note],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='latchline-set-note.txt';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 sync();
}
