import {practices,topics,jurisdictions,stages,windows,officialResource} from './data.js';
document.querySelectorAll('[data-showcase]').forEach(link=>{if(!location.pathname.startsWith('/showcase/products/'))link.href='/showcase/#work'});
const form=document.getElementById('scope-form');
if(form){
 const topic=document.getElementById('topic'),stage=document.getElementById('stage'),advisers=document.getElementById('advisers'),windowChoice=document.getElementById('window'),confirmation=document.getElementById('boundary-confirm'),error=document.getElementById('scope-error'),result=document.getElementById('scope-result'),status=document.getElementById('scope-status');
 let report=null;
 form.reset();document.getElementById('scope-fields').disabled=false;
 const query=new URLSearchParams(location.search);if(topics.some(t=>t.id===query.get('topic')))topic.value=query.get('topic');if(location.search)history.replaceState(null,'',location.pathname+location.hash);
 form.addEventListener('reset',()=>{report=null;result.hidden=true;result.innerHTML='';form.hidden=false;error.hidden=true;error.textContent='';status.textContent='Choices cleared. Nothing was sent or stored.'});
 window.addEventListener('pageshow',event=>{if(event.persisted)form.reset()});
 form.addEventListener('submit',event=>{
  event.preventDefault();
  const selectedTopic=topics.find(t=>t.id===topic.value),practice=practices.find(p=>p.id===topic.value),countries=jurisdictions.filter(j=>document.getElementById('jurisdiction-'+j.id).checked);
  let message='';
  if(!selectedTopic)message='Choose a topic before preparing the note.';
  else if(!(stage.value in stages))message='Choose the current project stage.';
  else if(!countries.length)message='Choose at least one jurisdiction or select other / not confirmed.';
  else if(!['appointed','seeking'].includes(advisers.value))message='Choose whether advisers are already appointed.';
  else if(!(windowChoice.value in windows))message='Choose an expected decision window.';
  else if(!confirmation.checked)message='Confirm the local, non-confidential and no-legal-advice boundary.';
  if(message){error.textContent=message;error.hidden=false;error.focus();return}
  error.hidden=true;
  const referralOnly=!practice,boundaryFirst=!countries.some(c=>c.id==='sg')||countries.some(c=>c.id==='other');
  const title=referralOnly?'A different provider is the next step.':boundaryFirst?'Confirm the geography before the scope.':'A commercial scope to discuss.';
  const kind=referralOnly?'Referral-only preparation':boundaryFirst?'Boundary-first preparation':'Commercial scope preparation';
  const countryRows=countries.map(c=>referralOnly?{...c,role:'Independent subject specialist',action:c.id==='other'?'Identify the relevant jurisdictions before choosing a provider. No geographical coverage is assumed.':'Identify an appropriate independent provider for '+selectedTopic.name.toLowerCase()+' in '+c.name+'. No assessment or referral is performed here.'}:c);
  const stageAction=referralOnly?'No commercial scope is proposed for this subject.':stages[stage.value].action;
  const subjectBoundary=referralOnly?selectedTopic.name+' falls outside our three commercial workstreams. This site cannot assess, receive or route the matter. Identify an appropriate independent provider for the relevant subject and jurisdiction.':practice.boundary;
  const geographicBoundary=boundaryFirst?'The selected geography does not match a fully identified Singapore-led example. Establish the countries, project owner and appropriate providers before assuming Meridian has a role.':'The selected jurisdictions fit the shape of our Singapore-led examples. This is not a coverage, capability or engagement confirmation; local review remains separately scoped.';
  const adviserAction=advisers.value==='appointed'?'Existing advisers: confirm each provider’s accepted scope, country responsibilities and preferred review handover. Avoid duplicating or assuming their work.':'No advisers appointed: identify appropriate independent providers and establish who will own local review before a document handover. No actual introduction is arranged here.';
  const timeAction=windowChoice.value==='urgent'?'This is not an urgent-response channel. A selected near-term deadline creates no commitment, appointment or extension. Use an appropriate real provider for time-sensitive needs.':windowChoice.value==='quarter'?'The next quarter is a planning preference. Confirm dependencies and an achievable scope with the responsible providers; no completion date is offered.':'No fixed decision window is selected. Clarify the next decision and the dependencies before discussing a timetable.';
  const questions=referralOnly?['Identify the subject category and relevant countries without providing confidential details here.','Find an appropriate independent provider through relevant official resources.','Ask that provider how to arrange a secure first contact and confirm its scope.']:practice.questions;
  const readiness=referralOnly?['I have identified the relevant subject category and jurisdictions.','I know this website does not assess or refer a real matter.','I will use an appropriate provider’s agreed contact channel.']:['I can state the business decision without naming parties here.','I have identified the jurisdictions and operating roles to confirm.','I can separate agreed intentions from open commercial questions.',advisers.value==='appointed'?'I can confirm the role of each already appointed adviser.':'I know which specialist provider roles still need to be identified.','I understand that written scope and a secure handover come later.'];
  report={title,kind,topic:selectedTopic.name,stage:stages[stage.value],stageAction,countries:countryRows,advisers:advisers.value==='appointed'?'Advisers already appointed':'Advisers not yet appointed',window:windows[windowChoice.value],subjectBoundary,geographicBoundary,adviserAction,timeAction,questions,readiness,deliverable:practice&&!referralOnly?practice.deliverable:'No commercial work product proposed'};
  result.innerHTML=`<div class="result-topline"><span>${kind}</span><span>Local note / Nothing sent</span></div><h2 id="result-title">${title}</h2><p>${selectedTopic.name}</p><dl class="summary-grid"><div><dt>Project stage</dt><dd>${report.stage.name}</dd></div><div><dt>Jurisdictions</dt><dd>${countries.map(c=>c.name).join(', ')}</dd></div><div><dt>Adviser position</dt><dd>${report.advisers}</dd></div><div><dt>Decision window</dt><dd>${report.window}</dd></div></dl><div class="boundary"><p><strong>${referralOnly?'Subject boundary':'Geographic boundary'}</strong></p><p>${referralOnly?subjectBoundary:geographicBoundary}</p></div>${referralOnly?'':`<h3>A possible work product</h3><p>${practice.deliverable}.${boundaryFirst?' Only after the geography and provider roles are confirmed.':' Its actual scope and fee would still need to be agreed.'}</p><p>${stages[stage.value].action}</p>`}<h3>${referralOnly?'A suitable next conversation':'Questions to put in the brief'}</h3><ol>${questions.map(q=>`<li>${q}</li>`).join('')}</ol><h3>Jurisdiction responsibilities</h3>${countryRows.map(c=>`<article class="jurisdiction-row"><h4>${c.name} / ${c.role}</h4><p>${c.action}</p></article>`).join('')}<h3>Provider and timing actions</h3><p>${adviserAction}</p><p>${timeAction}</p><div class="boundary"><p><strong>No legal conclusion:</strong> ${subjectBoundary}</p><p>This note does not confirm eligibility, a professional relationship, a referral or permission to proceed.</p></div><h3>Prepare for the conversation</h3><div class="checklist"><p class="progress-text" id="readiness-progress" role="status">0 of ${readiness.length} preparation items marked</p>${readiness.map((text,i)=>`<label class="ready-item"><input id="ready-${i}" type="checkbox" data-ready>${text}</label>`).join('')}</div><div class="buttons"><button class="button" type="button" data-download>Download scope note (TXT)</button><button class="button outline" type="button" data-edit>Edit choices</button><button class="button outline" type="button" data-clear>Clear and start again</button></div><p class="small" style="margin-top:22px">Choices and readiness marks stay on this page. Downloaded files remain on your device. No confidential details, message or legal advice are involved.</p><a class="text-link" href="${officialResource}" target="_blank" rel="noopener noreferrer">Official Singapore provider resources ↗</a>`;
  result.hidden=false;form.hidden=true;status.textContent='Your preparation note was created locally. Nothing was sent.';result.focus();
  const checkboxes=[...result.querySelectorAll('[data-ready]')];
  checkboxes.forEach(c=>c.addEventListener('change',()=>{document.getElementById('readiness-progress').textContent=checkboxes.filter(i=>i.checked).length+' of '+readiness.length+' preparation items marked'}));
  result.querySelector('[data-edit]').addEventListener('click',()=>{result.hidden=true;form.hidden=false;status.textContent='Editing the brief. Rebuilding resets preparation marks.';topic.focus()});
  result.querySelector('[data-clear]').addEventListener('click',()=>{form.reset();topic.focus()});
  result.querySelector('[data-download]').addEventListener('click',()=>{
   const note=['MERIDIAN BRIDGE COUNSEL - LOCAL SCOPE NOTE','Fictional firm / no legal advice / no engagement / nothing sent','',report.kind,report.title,'Topic: '+report.topic,'Stage: '+report.stage.name,'Jurisdictions: '+report.countries.map(c=>c.name).join(', '),'Advisers: '+report.advisers,'Decision window: '+report.window,'','PROPOSED WORK PRODUCT',report.deliverable,report.stageAction,'','QUESTIONS',...report.questions.map((q,i)=>(i+1)+'. '+q),'','JURISDICTION RESPONSIBILITIES',...report.countries.map(c=>c.name+' - '+c.role+'\n'+c.action),'','BOUNDARIES',report.subjectBoundary,report.geographicBoundary,'','NEXT ACTIONS',report.adviserAction,report.timeAction,'','PREPARATION ITEMS',...report.readiness.map((text,i)=>(checkboxes[i].checked?'[x] ':'[ ] ')+text),'','No provider, matter, deadline, referral or eligibility has been accepted. No confidential data was requested.','This downloaded file remains on your device; page choices disappear on refresh or departure.','Official Singapore provider resources: '+officialResource].join('\n');
   const url=URL.createObjectURL(new Blob([note],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='meridian-'+topic.value+'-scope.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='The scope note was downloaded to your device. Nothing was sent.';
  });
 });
}
