export const practices=[
{id:'distributor',number:'01',name:'Distributor agreement coordination',short:'Before the agreement, align the commercial picture.',summary:'A clear record of what the product owner, distributor and service team each intend to do.',fit:'For a Singapore-based business considering a regional distributor or reviewing how an existing channel will work.',inputs:['Product groups and intended customer channels.','Proposed territories and the people owning each commercial decision.','A high-level view of orders, after-sales service and returns.'],outputs:['Commercial responsibilities matrix.','Decision log separating agreed intentions from open questions.','Questions pack for the client’s separately appointed qualified counsel.'],questions:['Which product groups and channels are included in the commercial proposal?','Who owns customer communication, after-sales support and returns?','Which territory assumptions remain open for review?'],boundary:'No model contract, clause recommendation, enforceability opinion or guarantee that a distribution arrangement can proceed.',example:'spares',deliverable:'Distributor responsibilities and open-decision pack'},
{id:'service',number:'02',name:'Service alignment',short:'Make the handover as clear as the promise.',summary:'Connect the commercial scope, delivery responsibilities and review owners across a service arrangement.',fit:'For operating teams coordinating a service provider, customer and local delivery or support participant.',inputs:['The service intention and high-level deliverables.','The parties’ operational roles, without names or confidential terms on this site.','Known handover points and the decision the project needs to reach.'],outputs:['Service-scope and responsibility grid.','Acceptance and escalation question list.','An ordered review handover with named role owners to confirm offline.'],questions:['What deliverable is each operating role expected to own?','Who will confirm acceptance and handle an unresolved handover?','Which dependencies need a commercial decision before document review?'],boundary:'No review of uploaded contracts, interpretation of legal obligations or substitute for jurisdiction-specific advice.',example:'support',deliverable:'Service responsibility and handover grid'},
{id:'entry',number:'03',name:'Market-entry issue map',short:'Find the questions before they become assumptions.',summary:'Organise an early commercial plan into workstreams, dependencies and specialist questions.',fit:'For founders or operating leads examining a new regional market before committing to a detailed implementation plan.',inputs:['The proposed activity and the next business decision.','The countries being considered and any local participant roles.','Known dependencies, uncertainties and already appointed advisers.'],outputs:['Commercial issue map and sequence of decisions.','A referral brief grouped by specialist category.','A record of questions that remain unanswered.'],questions:['What activity is being considered, and what decision comes next?','Which local participants and operating dependencies are assumed?','Which questions need local legal, tax or product/regulatory review?'],boundary:'No recommended entity structure, licensing conclusion, tax position, entry approval or assurance that a proposed activity is permitted.',example:'packaging',deliverable:'Market-entry questions and referral map'}
];
export const topics=[...practices.map(p=>({id:p.id,name:p.name})),{id:'dispute',name:'Dispute or litigation'},{id:'immigration',name:'Personal immigration'}];
export const jurisdictions=[
{id:'sg',name:'Singapore',role:'Project sponsor and coordination point',action:'Confirm the commercial owner, the intended decision and who is separately responsible for any Singapore-law review.'},
{id:'my',name:'Malaysia',role:'Local operating or distributor participant',action:'Identify the Malaysia-side operating role and an appropriate independent reviewer for Malaysia-specific questions.'},
{id:'id',name:'Indonesia',role:'Local service or operating participant',action:'Identify the Indonesia-side handover owner and confirm the scope and document language with an independent local reviewer.'},
{id:'vn',name:'Vietnam',role:'Local trading or operating participant',action:'Identify the Vietnam-side commercial assumptions and the independent reviewer responsible for local questions.'},
{id:'other',name:'Other or not confirmed',role:'Geography remains unconfirmed',action:'Identify the relevant countries and suitable providers first. No additional jurisdiction or referral relationship is assumed.'}
];
export const stages={exploring:{name:'Exploring the idea',action:'Start with the intended business decision and record assumptions before creating a detailed document brief.'},aligning:{name:'Aligning commercial roles',action:'Separate agreed intentions from open decisions and assign an operating owner to each handover.'},review:{name:'Preparing for document review',action:'Confirm the version, review owner and list of unresolved commercial questions before sharing anything through an agreed secure channel.'}};
export const windows={flexible:'No fixed decision window',quarter:'Planning within the next quarter',urgent:'A near-term or urgent deadline'};
export const officialResource='https://www.mlaw.gov.sg/news/announcements/legal-support-resources-available-to-members-of-the-public/';
