import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
export const nav=[['index.html','Home'],['practice.html','Practice'],['cross-border.html','Cross-border work'],['engagement.html','Engagement'],['firm.html','The firm'],['enquiry.html','Prepare an enquiry ↗']];
export const img=(name,alt,extra='')=>`<img src="assets/${name}.webp" srcset="assets/${name}-768.webp 768w, assets/${name}.webp 1536w" sizes="(max-width:700px) 100vw, 80vw" width="1536" height="1024" alt="${alt}" ${extra}>`;
export const button=(href,label,outline=false)=>`<a class="button${outline?' outline':''}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
export const intro=(label,title,text)=>`<div class="page-intro"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${text}</p></div>`;
export const cta=(title='Begin with the question.<br>Then define the work.')=>`<section class="cta"><h2>${title}</h2>${button('enquiry.html','Prepare a non-confidential enquiry')}</section>`;
const version=createHash('sha256').update(await readFile(new URL('site.css',import.meta.url))).digest('hex').slice(0,8);
export async function page(path,title,description,body){await writeFile(new URL(path,import.meta.url),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${description}"><meta name="theme-color" content="#5c2432"><title>${title} | Meridian Bridge Counsel</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="assets/fonts/source-serif.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="site.css?v=${version}"><script type="module" src="app.js?v=${version}"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="masthead"><div class="wrap"><div class="masthead-row"><a class="wordmark" href="index.html" aria-label="Meridian Bridge Counsel home">Meridian Bridge<small>COUNSEL</small></a><div class="office-note">Singapore<br>Commercial coordination<br>Regional perspective</div></div><nav class="main-nav" aria-label="Main navigation">${nav.map(([href,label])=>`<a href="${href}"${href===path?' aria-current="page"':''}>${label}</a>`).join('')}</nav></div></header><main id="main" tabindex="-1">${body}</main><footer class="footer"><div class="wrap"><div class="footer-grid"><div><a class="wordmark" href="index.html">Meridian Bridge<small>COUNSEL</small></a><p>Commercial questions. Defined responsibilities.<br>Singapore · Established 2020</p></div><div><h2>Explore the work</h2><nav class="footer-links" aria-label="Footer navigation"><a href="practice.html">Three commercial workstreams</a><a href="cross-border.html">Regional examples</a><a href="engagement.html">How engagement is scoped</a></nav></div><div><h2>A first conversation</h2><a class="text-link" href="enquiry.html">Prepare an enquiry ↗</a><p>Example contact only:<br>scope@meridianbridge.example</p></div></div><div class="footer-meta"><p id="concept">Fictional advisory firm / concept website. No real lawyers, licences, clients or credentials are represented. Images depict generated fictional settings. This is not a licensed legal practice or a source of legal advice. The local planner sends nothing and forms no engagement; choices are discarded on refresh or departure.</p><a href="/#work" data-showcase>Return to Showcase ↗</a></div></div></footer></body></html>`,'utf8')}
