export const services=[
 {id:'storage',name:'Storage Start',verb:'A place for steady stock.',description:'Pallet receiving, agreed storage locations and release instructions for regular B2B inventory.',fit:'Packaged stock held in pallet quantities, with a defined owner and a predictable release pattern.',inputs:'A stock master, pallet dimensions and weights, arrival outline and authorised release contacts.',output:'An opening stock record, agreed location method and a pallet release handover.',check:'Confirm pallet identity and receiving discrepancies before the starting stock record is agreed.'},
 {id:'picking',name:'Pick & Pack',verb:'The right units, ready to hand over.',description:'Carton-level order preparation for defined stock lines, with agreed picking and pack rules.',fit:'Small B2B orders that combine stock lines and need a consistent carton handover.',inputs:'SKU and variant labels, order examples, packing instructions and the customer’s carrier requirements.',output:'A documented pick/pack method, sample order walkthrough and dispatch handover checklist.',check:'Agree the SKU-to-carton rules and how order discrepancies are returned for a decision.'},
 {id:'project',name:'Project Stock',verb:'A plan for the next release.',description:'Separately identified campaign stock, staged release batches and an organised close-out.',fit:'A defined rollout or campaign with stock reserved by project and release batches agreed in advance.',inputs:'A project stock list, release sequence, batch owners and a plan for residual stock.',output:'A project stock index, batch release checklist and campaign close-out record.',check:'Assign each release batch an owner and agree the treatment of unallocated stock.'}
];
export const zones=[
 {id:'receiving',name:'Receiving',area:1200,number:'01',activity:'Check the arrival before it becomes stock.',detail:'Match the arrival outline, count the units and record visible discrepancies for the stock owner. A receipt is not a silent acceptance of an unexplained difference.',handover:'Arrival outline, pallet identifiers, carton counts and a discrepancy contact.'},
 {id:'storage',name:'Storage',area:4800,number:'02',activity:'Give each agreed stock unit a place.',detail:'Locate identified pallets according to the agreed stock profile. Product dimensions, weight and handling needs determine the discussion; floor area alone does not establish pallet capacity.',handover:'Agreed stock master, unit dimensions and weights, and release authority.'},
 {id:'packing',name:'Pick & pack',area:1000,number:'03',activity:'Turn an order into a defined handover.',detail:'Select the agreed stock lines, follow the packing instructions and flag any mismatch before a carton is released. This is a concept workflow, not a live order system.',handover:'Sample order, SKU-to-pack rules, label requirements and exception owner.'},
 {id:'dispatch',name:'Dispatch',area:1000,number:'04',activity:'Stage the release for the next owner.',detail:'Group the prepared units by release instruction and document the carrier handover. Transport is separately arranged by the customer; no delivery time is guaranteed here.',handover:'Release instruction, collection arrangement and carrier handover record.'}
];
export const goods=[{id:'homewares',name:'Dry packaged homewares',review:'Confirm carton integrity and review any fragile-item packing.'},{id:'parts',name:'Non-hazardous metal spare parts',review:'Confirm unit weights, identification and handling requirements.'},{id:'textiles',name:'Packaged textiles',review:'Agree size/variant labels and carton grouping.'},{id:'restricted',name:'Restricted or temperature-controlled goods',review:'Outside scope: no food, cold chain, medicines, dangerous goods or live animals.'}];
