export const fee=value=>`€${value.toFixed(2)}`;
export const sessions={
 first:{name:'First conversation',label:'Initial movement consultation',duration:50,fee:78,image:'conversation',audience:'First visits, or a returning visitor starting a new conversation.',description:'Time to talk about the everyday activities that matter to you, ask questions and consider a sensible next step together. You do not need to arrive with a finished plan.',agenda:[{minutes:10,title:'Settle in',text:'Get comfortable and share the questions you want to discuss.'},{minutes:25,title:'Talk and look together',text:'Discuss your priorities and agree which everyday movements to look at in the room.'},{minutes:15,title:'Leave with clarity',text:'Make time for questions and a summary of the next steps discussed.'}],scope:['A one-to-one conversation in the studio','Time to discuss ordinary activity priorities','A clear summary of the next-step discussion'],limits:'No predetermined programme, online diagnosis, exercise prescription or promised number of follow-up visits.',prepare:'Bring two or three questions about the everyday activities you want to discuss. No medical details are entered into this website.',alt:'Two adults sitting in a warm room for an unhurried first conversation.'},
 supported:{name:'Supported movement',label:'One-to-one activity session',duration:40,fee:56,image:'movement',audience:'Returning visitors with an agreed studio session plan.',description:'A dedicated studio visit to work through activities already agreed with your session team. There is room to ask questions as you go, then review what to discuss at the next visit.',agenda:[{minutes:5,title:'Check in',text:'Talk through the focus of the agreed session.'},{minutes:30,title:'Work through the plan',text:'Spend time on the previously agreed activities with one-to-one supervision.'},{minutes:5,title:'Review your questions',text:'Summarise the session and anything to discuss next time.'}],scope:['One-to-one time in the movement room','Supervision of a previously agreed activity plan','A short review before you leave'],limits:'Not a drop-in class, independent gym session, remote supervision or guarantee of improvement. An initial studio visit comes first.',prepare:'Keep the practical questions from your last studio visit ready. This website does not provide or alter your exercise plan.',alt:'An adult visitor and studio team member talking beside a chair in the movement room.'},
 review:{name:'Review & refine',label:'Existing activity-plan review',duration:25,fee:42,image:'preparation',audience:'Returning visitors with an existing agreed activity plan.',description:'A shorter conversation about the plan you already have. Bring the questions that have come up so there is a clear place to revisit the details with your session team.',agenda:[{minutes:5,title:'Check in',text:'Agree the questions to cover in this review.'},{minutes:15,title:'Look at the existing plan',text:'Discuss the plan already agreed and the points you want to clarify.'},{minutes:5,title:'Summarise',text:'Recap what was discussed and the next conversation, if one is needed.'}],scope:['A focused one-to-one review conversation','Time for questions about an existing plan','A short summary of the discussion'],limits:'Not a new diagnostic assessment, automatic progression or online plan review. Do not upload a plan or health information here.',prepare:'Bring your existing questions and any session notes you choose to use in person. Do not send or upload them through this concept website.',alt:'A notebook, water bottle, comfortable top and ordinary trainers ready for a studio visit.'}
};
export const visitTypes={first:'First visit',returning:'Returning visitor'};
export const times={morning:'Weekday morning',afternoon:'Weekday afternoon',outside:'Evening or weekend'};
export const languages={english:'English',dutch:'Dutch'};
export const arrivals={walk:'On foot or by cycle',transit:'Public transport',dropoff:'Being dropped off'};
export const logistics={entry:{label:'Ask about step-free entry',text:'Ask the coordinator to check the entrance, room route and any dimensions you need before attending.'},quiet:{label:'Ask about quieter waiting',text:'Discuss whether a quieter arrival or waiting arrangement can be made; this note does not confirm it.'},companion:{label:'Ask about a companion seat',text:'Discuss space for a companion and how you would like them involved before your visit.'}};
