import {challenges,contexts,sites,modes} from './data.js';
document.querySelectorAll('[data-showcase]').forEach(link=>{if(!location.pathname.startsWith('/showcase/products/'))link.href='/showcase/#work'});
const form=document.getElementById('brief-form');
if(form){
 const controls=Object.fromEntries(['challenge','context','sites','people','mode','evidence'].map(id=>[id,document.getElementById(id)]));const confirm=document.getElementById('local-confirm'),error=document.getElementById('brief-error'),result=document.getElementById('brief-result'),status=document.getElementById('brief-status');
 form.reset();document.getElementById('brief-fields').disabled=false;
 const query=new URLSearchParams(location.search);if(challenges.some(c=>c.id===query.get('challenge')))controls.challenge.value=query.get('challenge');if(location.search)history.replaceState(null,'',location.pathname+location.hash);
 form.addEventListener('reset',()=>{result.hidden=true;result.innerHTML='';form.hidden=false;error.hidden=true;status.textContent='Choices cleared. Nothing was sent or stored.'});
 window.addEventListener('pageshow',event=>{if(event.persisted)form.reset()});
 form.addEventListener('submit',event=>{
  event.preventDefault();const c=challenges.find(c=>c.id===controls.challenge.value),people=Number(controls.people.value);let message='';
  if(!c)message='Choose the main operating challenge.';else if(!(controls.context.value in contexts))message='Choose the organisation context.';else if(!(controls.sites.value in sites))message='Choose how many sites are involved.';else if(!Number.isInteger(people)||people<2||people>12)message='Enter a whole number from 2 to 12 people.';else if(!(controls.mode.value in modes))message='Choose a working preference.';else if(!['ready','missing'].includes(controls.evidence.value))message='Choose whether an example can be prepared.';else if(!confirm.checked)message='Confirm the local preparation and no-diagnosis boundary.';
  if(message){error.textContent=message;error.hidden=false;error.focus();return}
  error.hidden=true;const boundary=controls.context.value==='other',wide=controls.sites.value==='network',large=people>8,missing=controls.evidence.value==='missing',remote=controls.mode.value==='remote';
  const title=boundary?'Confirm the fit before the workshop.':'A discussion with a clear starting point.';
  const agenda=boundary?[['Describe the organisation and question',20],['Identify which expertise is actually needed',25],['Clarify the responsibility boundary',25],['Agree an appropriate next conversation',20]]:c.agenda;
  const outputs=boundary?['A subject-fit question list.','A record of expertise and scope still to confirm.']:c.outputs;
  const siteAction=wide?'A wider network needs a scope discussion first. Identify one representative pilot area before assuming a common approach across four or more sites.':controls.sites.value==='one'?'Keep the first working example within the selected site.':`Compare the handovers across ${sites[controls.sites.value].toLowerCase()} and choose one working example to discuss first.`;
  const groupAction=large?`With ${people} people, prepare in two smaller groups before the joint discussion. The 90-minute agenda is the joint session only; preparatory time is not included.`:`For ${people} people, invite the receiving roles and a decision owner to one focused discussion. Confirm that each person has a useful role.`;
  const evidenceAction=boundary?'Describe the subject and the expertise needed without sharing real operational information here. Agree appropriate evidence with the provider identified.':missing?'Before a workshop, agree how to create an anonymised walkthrough. No usable example is ready yet; do not treat this note as evidence of the operating problem.':c.evidence+' Keep real operational material out of this website.';
  const modeAction=remote?'For a remote discussion, agree a shared document and a facilitator. This plan includes no on-site observation.':'For an on-site discussion, agree access and a suitable working setting with the site owner. Site access is not booked here.';
  const scopeAction=boundary?'This organisation is outside our defined maker/distributor remit. No standard engagement sequence or working-document commitment is proposed.':wide?'Confirm a bounded pilot and its timetable before using any example engagement sequence.':`The ${c.weeks}-week ${c.name} sequence is an example for discussion, not a reserved timetable or delivery promise.`;
  const roles=boundary?['A person who can describe the organisation’s question','An appropriate subject specialist to identify','The person responsible for deciding the next step']:c.roles;
  const total=agenda.reduce((sum,step)=>sum+step[1],0);
  result.innerHTML=`<span class="result-kicker">${boundary?'Subject-fit preparation':c.name+' / Discussion preparation'}</span><h2 id="result-title">${title}</h2><dl class="result-meta"><div><dt>Selected challenge</dt><dd>${c.name}</dd></div><div><dt>Organisation</dt><dd>${contexts[controls.context.value]}</dd></div><div><dt>Sites</dt><dd>${sites[controls.sites.value]}</dd></div><div><dt>Group</dt><dd>${people} people / ${modes[controls.mode.value]}</dd></div></dl><div class="boundary"><p>${scopeAction}</p></div><h3>${boundary?'A fit discussion agenda':'An illustrative scoping agenda'}</h3><ol class="agenda">${agenda.map(([text,minutes])=>`<li><strong>${minutes} min</strong><span>${text}</span></li>`).join('')}</ol><div class="agenda-total">${total} minutes total / Preparation time not included</div><h3>${boundary?'What to clarify':'Working outputs to discuss'}</h3><ul>${outputs.map(o=>`<li>${o}</li>`).join('')}</ul><h3>Who needs a useful invitation?</h3><ul>${roles.map(r=>`<li>${r}</li>`).join('')}</ul><h3>Prepare the conversation</h3><p>${siteAction}</p><p>${groupAction}</p><p>${evidenceAction}</p><p>${modeAction}</p><div class="boundary"><p>No operational diagnosis, savings forecast, access, meeting or engagement has been accepted. A real scope, fee and handling arrangement would be agreed separately.</p></div><div class="buttons"><button class="button" type="button" data-download>Download discussion note (TXT)</button><button class="button outline" type="button" data-edit>Edit choices</button><button class="button outline" type="button" data-clear>Clear and start again</button></div>`;
  form.hidden=true;result.hidden=false;status.textContent='Your note was prepared on this page. Nothing was sent.';result.focus();
  result.querySelector('[data-edit]').addEventListener('click',()=>{form.hidden=false;result.hidden=true;status.textContent='Editing your choices.';controls.challenge.focus()});
  result.querySelector('[data-clear]').addEventListener('click',()=>{form.reset();controls.challenge.focus()});
  result.querySelector('[data-download]').addEventListener('click',()=>{
   const note=['QUOINMERE OPERATIONS - LOCAL DISCUSSION NOTE','Fictional consultancy. No diagnosis or engagement. Nothing sent.','',title,'Challenge: '+c.name,'Context: '+contexts[controls.context.value],'Sites: '+sites[controls.sites.value],'People: '+people,'Preference: '+modes[controls.mode.value],'',scopeAction,'','AGENDA',...agenda.map(([text,minutes])=>minutes+' min - '+text),'Total: '+total+' minutes; preparation time not included.','','WORKING OUTPUTS',...outputs,'','INVITATIONS',...roles,'','PREPARATION',siteAction,groupAction,evidenceAction,modeAction,'','Choices disappear on refresh or departure. This downloaded file remains on your device.','No real operational information was collected; no email, booking or CRM was used.'].join('\n');
   const url=URL.createObjectURL(new Blob([note],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='quoinmere-'+c.id+'-discussion.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='The note was downloaded to your device. Nothing was sent.';
  });
 });
}
