document.documentElement.classList.add('js-ready');
const menu=document.querySelector('.menu');const nav=document.querySelector('#navigation');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav?.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus();}});
if(!location.pathname.includes('/showcase/products/'))document.querySelectorAll('[data-showcase]').forEach(link=>link.href='/showcase/#work');
const $=id=>document.getElementById(id);const money=value=>'€'+value.toFixed(2);
function garmentTable(g,selected=''){return `<div class="table-wrap"><table><caption>${g.name} · nominal garment measurements in cm</caption><thead><tr><th scope="col">Size</th>${g.headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${g.sizes.map(size=>`<tr class="${size.id===selected?'selected':''}"><th scope="row">${size.id}</th>${size.values.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const fitForm=$('fit-form');
if(fitForm){
 const garments=JSON.parse($('fit-data').textContent);const fields={garment:$('fit-garment'),size:$('fit-size'),known:$('known-measure')};
 const selected=()=>garments.find(g=>g.id===fields.garment.value);
 function clearResult(){$('fit-output').hidden=true;$('fit-empty').hidden=false;$('fit-error').hidden=true;Object.values(fields).forEach(field=>field.removeAttribute('aria-invalid'));}
 function preview(){const g=selected();const size=g?.sizes.find(s=>s.id===fields.size.value);$('fit-preview').hidden=!size;if(size){$('fit-preview-title').textContent=g.name+' · '+size.id;$('fit-drawing').innerHTML=globalThis.spliceDrawing(g,size);$('fit-selected-table').innerHTML=garmentTable(g,size.id);}}
 function options(){const g=selected();fields.size.replaceChildren(new Option(g?'Choose a size':'Choose a garment first',''));fields.size.disabled=!g;fields.known.disabled=!g;fields.known.value='';if(g){for(const size of g.sizes)fields.size.add(new Option(size.id,size.id));fields.known.min=g.min;fields.known.max=g.max;$('measure-label').textContent=`Your garment's ${g.measure.toLowerCase()} (cm)`;$('measure-help').textContent=g.measureHelp+` Enter ${g.min}–${g.max}cm.`;}else{$('measure-label').textContent="Your existing garment's flat width (cm)";$('measure-help').textContent='Choose a garment to see which dimension to measure.';}clearResult();preview();}
 function reset(){fitForm.reset();options();}
 reset();$('compare-button').disabled=false;$('clear-fit').disabled=false;const initial=garments.find(g=>g.id===new URLSearchParams(location.search).get('garment'));if(initial){fields.garment.value=initial.id;options();}if(location.search)history.replaceState(null,'',location.pathname);
 fields.garment.addEventListener('change',options);fields.size.addEventListener('change',()=>{clearResult();preview();});fields.known.addEventListener('input',clearResult);
 function invalid(field,text){fields[field].setAttribute('aria-invalid','true');$('fit-error').textContent=text;$('fit-error').hidden=false;fields[field].focus();}
 fitForm.addEventListener('submit',event=>{event.preventDefault();clearResult();const g=selected();if(!g)return invalid('garment','Choose a garment to compare.');const size=g.sizes.find(s=>s.id===fields.size.value);if(!size)return invalid('size','Choose one of the four listed Sunday Splice sizes.');const known=Number(fields.known.value);if(!fields.known.value||!Number.isFinite(known)||known<g.min||known>g.max)return invalid('known',`Enter a flat garment measurement from ${g.min} to ${g.max}cm.`);const difference=Math.round((size.values[0]-known)*10)/10;$('fit-title').textContent=`${g.name} · ${size.id}`;$('fit-difference').textContent=difference===0?'Same listed width.':`${Math.abs(difference).toFixed(1)}cm ${difference>0?'wider':'narrower'}`;$('fit-description').textContent=`Your garment measures ${known.toFixed(1)}cm at the ${g.measure.toLowerCase()}. This ${g.name} size ${size.id} is listed at ${size.values[0]}cm at the same point. ${g.id==='trouser'?'This compares relaxed waistbands, not the extended value or your body.':'The comparison is across the laid-flat garment, not around your body.'}`;$('fit-output').hidden=false;$('fit-empty').hidden=true;$('fit-to-bag').href=`demo-bag.html?garment=${g.id}&size=${size.id}`;preview();$('fit-title').focus();});
 $('edit-fit').addEventListener('click',()=>{clearResult();fields.known.focus();});$('clear-fit').addEventListener('click',()=>{reset();fields.garment.focus();});window.addEventListener('pageshow',event=>{if(event.persisted)reset();});
}
const bagForm=$('bag-form');
if(bagForm){
 const garments=JSON.parse($('bag-data').textContent);const fields=Object.fromEntries(['garment','colour','size','quantity'].map(id=>[id,$(id)]));let cart=[];let editing=-1;
 const selected=()=>garments.find(g=>g.id===fields.garment.value);
 function errorClear(){$('bag-error').hidden=true;Object.values(fields).forEach(field=>field.removeAttribute('aria-invalid'));}
 function options(){const g=selected();fields.colour.replaceChildren(new Option(g?'Choose a colour':'Choose a garment first',''));fields.size.replaceChildren(new Option(g?'Choose a size':'Choose a garment first',''));fields.colour.disabled=!g;fields.size.disabled=!g;if(g){for(const colour of g.colours)fields.colour.add(new Option(colour.name,colour.id));for(const size of g.sizes)fields.size.add(new Option(size.id,size.id));}}
 function preview(){const g=selected();$('bag-preview').hidden=!g;if(!g)return;$('bag-image').src=`assets/images/${g.id}-768.webp`;$('bag-image').alt=`${g.name}, ${g.colours[0].name} left and ${g.colours[1].name} right`;$('bag-piece-title').textContent=g.name;const colour=g.colours.find(c=>c.id===fields.colour.value);const size=g.sizes.find(s=>s.id===fields.size.value);$('bag-variant').textContent=[colour?.name,size?'Size '+size.id:null].filter(Boolean).join(' · ')||'Choose a colour and size.';$('bag-measure').textContent=size?g.headers.map((header,index)=>`${header}: ${size.values[index]}cm`).join(' / '):'Dimensions appear once you choose a size.';$('bag-caption').textContent=`Both colours shown: ${g.colours[0].name} left, ${g.colours[1].name} right. No image-based fit claim.`;$('unit-price').textContent=money(g.price)+' per garment';}
 function chooserReset(){bagForm.reset();editing=-1;options();preview();errorClear();$('chooser-title').textContent='Choose your piece';$('add-garment').innerHTML='Add to demo bag <span aria-hidden="true">↗</span>';$('cancel-edit').hidden=true;}
 function lineDetails(line){const g=garments.find(item=>item.id===line.garment);return {g,colour:g.colours.find(c=>c.id===line.colour),size:g.sizes.find(s=>s.id===line.size)};}
 function key(line){return [line.garment,line.colour,line.size].join(':');}
 function render(){
  $('empty-bag').hidden=!!cart.length;$('totals').hidden=!cart.length;$('review-bag').disabled=editing>=0;
  $('cart-lines').innerHTML=cart.map((line,index)=>{const {g,colour,size}=lineDetails(line);return `<article class="cart-line"><div class="cart-top"><div><h3>${g.name}</h3><p>${colour.name} · Size ${size.id} · ${money(g.price)} each</p></div><strong>${money(line.quantity*g.price)}</strong></div><div class="cart-controls"><label for="line-qty-${index}">Quantity <select id="line-qty-${index}" data-quantity="${index}" ${editing>=0?'disabled':''}>${[1,2,3,4,5].map(q=>`<option value="${q}" ${line.quantity===q?'selected':''}>${q}</option>`).join('')}</select></label><button class="plain" data-edit="${index}" type="button" aria-label="Edit ${g.name}, ${colour.name}, size ${size.id}" ${editing>=0?'disabled':''}>Edit variant</button><button class="plain" data-remove="${index}" type="button" aria-label="Remove ${g.name}, ${colour.name}, size ${size.id}" ${editing>=0?'disabled':''}>Remove</button></div></article>`;}).join('');
  const total=cart.reduce((sum,line)=>sum+lineDetails(line).g.price*line.quantity,0);const count=cart.reduce((sum,line)=>sum+line.quantity,0);$('bag-total').textContent=money(total);$('bag-count').textContent=`${count} ${count===1?'garment':'garments'} · ${cart.length} ${cart.length===1?'variant':'variants'}`;
 }
 function reset(){cart=[];chooserReset();render();$('review').hidden=true;$('bag-layout').hidden=false;$('bag-status').textContent='';$('download-status').textContent='';}
 reset();$('add-garment').disabled=false;const params=new URLSearchParams(location.search);const initial=garments.find(g=>g.id===params.get('garment'));if(initial){fields.garment.value=initial.id;options();const size=initial.sizes.find(s=>s.id===params.get('size'));if(size)fields.size.value=size.id;preview();}if(location.search)history.replaceState(null,'',location.pathname);
 fields.garment.addEventListener('change',()=>{options();preview();errorClear();});bagForm.addEventListener('input',()=>{errorClear();preview();});bagForm.addEventListener('change',()=>{errorClear();preview();});
 function invalid(field,text){fields[field].setAttribute('aria-invalid','true');$('bag-error').textContent=text;$('bag-error').hidden=false;fields[field].focus();}
 bagForm.addEventListener('submit',event=>{event.preventDefault();errorClear();const g=selected();if(!g)return invalid('garment','Choose a garment before adding it.');const colour=g.colours.find(c=>c.id===fields.colour.value);if(!colour)return invalid('colour','Choose one of this garment’s two colours.');const size=g.sizes.find(s=>s.id===fields.size.value);if(!size)return invalid('size','Choose XS, S, M or L for this garment.');const quantity=Number(fields.quantity.value);if(!Number.isInteger(quantity)||quantity<1||quantity>5)return invalid('quantity','Choose a whole quantity from 1 to 5.');const line={garment:g.id,colour:colour.id,size:size.id,quantity};const other=cart.findIndex((entry,index)=>index!==editing&&key(entry)===key(line));if(other>=0&&cart[other].quantity+quantity>5)return invalid('quantity','The combined variant would exceed 5 garments. Lower the quantity or edit the existing line.');const wasEdit=editing>=0;
  if(other>=0){cart[other].quantity+=quantity;if(wasEdit)cart.splice(editing,1);}else if(wasEdit)cart[editing]=line;else cart.push(line);
  if(wasEdit)chooserReset();render();$('bag-status').textContent=`${g.name}, ${colour.name}, size ${size.id} ${wasEdit?'updated in':'added to'} your local demo bag.`;
 });
 $('cart-lines').addEventListener('change',event=>{const target=event.target;if(!(target instanceof HTMLSelectElement)||!target.matches('[data-quantity]'))return;const index=Number(target.dataset.quantity);const quantity=Number(target.value);if(Number.isInteger(quantity)&&quantity>=1&&quantity<=5&&cart[index]){cart[index].quantity=quantity;render();$('bag-status').textContent='Quantity changed. Your item total has been updated.';}});
 $('cart-lines').addEventListener('click',event=>{const target=event.target.closest('button');if(!target||target.disabled)return;const remove=target.dataset.remove;if(remove!==undefined){cart.splice(Number(remove),1);render();$('bag-status').textContent='The selected variant was removed.';return;}const index=Number(target.dataset.edit);const line=cart[index];if(!line)return;editing=index;fields.garment.value=line.garment;options();fields.colour.value=line.colour;fields.size.value=line.size;fields.quantity.value=line.quantity;preview();errorClear();$('chooser-title').textContent='Edit this variant';$('add-garment').innerHTML='Save these changes <span aria-hidden="true">↗</span>';$('cancel-edit').hidden=false;render();$('bag-status').textContent='Save or cancel these changes before reviewing the bag.';fields.garment.focus();});
 $('cancel-edit').addEventListener('click',()=>{chooserReset();render();$('bag-status').textContent='Changes cancelled. Your bag is unchanged.';});
 $('clear-bag').addEventListener('click',()=>{reset();fields.garment.focus();});$('clear-review').addEventListener('click',()=>{reset();fields.garment.focus();});
 $('review-bag').addEventListener('click',()=>{if(!cart.length||editing>=0)return;$('review-lines').innerHTML=cart.map(line=>{const {g,colour,size}=lineDetails(line);return `<article class="review-line"><div><h3>${g.name}</h3><p>${colour.name} · Size ${size.id} · ${line.quantity} ${line.quantity===1?'garment':'garments'} × ${money(g.price)}</p><p>${g.headers.map((header,index)=>`${header}: ${size.values[index]}cm`).join(' / ')}</p></div><strong>${money(g.price*line.quantity)}</strong></article>`;}).join('');$('review-total').textContent=$('bag-total').textContent;$('bag-layout').hidden=true;$('review').hidden=false;$('download-status').textContent='';$('review-title').focus();});
 $('keep-choosing').addEventListener('click',()=>{$('review').hidden=true;$('bag-layout').hidden=false;fields.garment.focus();});
 $('download-bag').addEventListener('click',()=>{if(!cart.length)return;const lines=['SUNDAY SPLICE — LOCAL DEMO BAG','Fictional clothing label / illustrative item prices in EUR',''];for(const line of cart){const {g,colour,size}=lineDetails(line);lines.push(`${g.name} · ${colour.name} · Size ${size.id} · ${line.quantity} ${line.quantity===1?'garment':'garments'}`,`${money(g.price)} each; line total ${money(g.price*line.quantity)}`,g.headers.map((header,index)=>`${header}: ${size.values[index]}cm`).join(' / '),'');}lines.push('Item total: '+$('bag-total').textContent,'','No order, payment, live stock, tax calculation, discount or shipping is created. Nominal garment dimensions are not a body-fit guarantee. No personal data is collected. Bag state disappears on refresh or departure; this file remains on your device.');const objectUrl=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=objectUrl;link.download='sunday-splice-demo-bag.txt';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);$('download-status').textContent='Your itemised edit was prepared as a TXT download. No order was placed.';});
 window.addEventListener('pageshow',event=>{if(event.persisted)reset();});
}
