import {products,money} from './data.js';
const key='stillfern-demo-v1';
let bag={items:{},delivery:'standard'},persistent=true;
try{const parsed=JSON.parse(sessionStorage.getItem(key)||'null');if(parsed&&typeof parsed.items==='object'){for(const p of products){const q=parsed.items[p.id];if(Number.isInteger(q)&&q>=1&&q<=6)bag.items[p.id]=q;}if(parsed.delivery==='tracked')bag.delivery='tracked';}sessionStorage.setItem(key,JSON.stringify(bag));}catch{persistent=false;}
const count=()=>Object.values(bag.items).reduce((a,b)=>a+b,0);
const save=()=>{try{sessionStorage.setItem(key,JSON.stringify(bag));}catch{persistent=false;}document.querySelectorAll('[data-bag-count]').forEach(el=>el.textContent=count());const note=document.querySelector('[data-storage]');if(note)note.textContent=persistent?'Your bag stays in this browser tab during its session, including refreshes. Nothing is sent.':'Browser storage is unavailable. Choices remain on this page only and may reset when you navigate. Nothing is sent.';};
save();
for(const form of document.querySelectorAll('.add-form'))form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const id=form.dataset.product,q=Number(new FormData(form).get('quantity')),status=form.querySelector('[role=status]');if(!Number.isInteger(q)||q<1||q>6)return;if((bag.items[id]||0)+q>6){status.textContent='The demo limit is six of each product. Adjust the quantity in your bag first.';return;}bag.items[id]=(bag.items[id]||0)+q;save();status.textContent=`${q} added. Your demo bag has ${count()} ${count()===1?'item':'items'}.`+(!persistent?' Browser storage is unavailable; this selection stays on this page only. Use the routine buttons on the bag page to build and download a note there.':'');});
for(const button of document.querySelectorAll('[data-filter]'))button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let visible=0;document.querySelectorAll('[data-area]').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.area!==button.dataset.filter;if(!card.hidden)visible++;});document.querySelector('#filter-result').textContent=`${visible} ${visible===1?'product':'products'}`;});
const contact=document.querySelector('#contact-form');
if(contact){const answers={product:['Product information','Each product page includes its amount, texture, use and complete illustrative ingredient list. Start there to compare formats. This concept site cannot assess individual skin needs.','products.html','Compare the collection'],delivery:['Delivery & the demo bag','Standard delivery is £4.50, free from a £50 product subtotal; tracked is £7.00. The bag saves only in this tab session. No actual order or delivery is created.','bag.html','Try the demo bag'],retail:['A small retail enquiry','A real conversation would begin with your UK shop location, shelf space and which of the three products you would like to carry. Here you can review the catalogue, but no retailer application or message is sent.','products.html','Review the three-product catalogue']};const select=contact.querySelector('select');const query=new URLSearchParams(location.search).get('topic');if(Object.hasOwn(answers,query))select.value=query;const show=()=>{const [title,copy,href,label]=answers[select.value];document.querySelector('#contact-answer').innerHTML=`<h2>${title}</h2><p>${copy}</p><a class="text-link" href="${href}">${label} ↗</a>`;};show();contact.addEventListener('submit',event=>{event.preventDefault();show();});select.addEventListener('change',()=>{document.querySelector('#contact-answer').textContent='Topic changed. Choose “Show the next steps” to see the relevant information.';});}
const rows=document.querySelector('#bag-items');
if(rows){let receiptText='';const receipt=document.querySelector('#receipt'),error=document.querySelector('#bag-error'),delivery=document.querySelector('#delivery');delivery.value=bag.delivery;
 const invalidate=()=>{receipt.hidden=true;receiptText='';error.textContent='';};
 const valid=()=>[...rows.querySelectorAll('input')].every(input=>input.validity.valid&&Number.isInteger(Number(input.value)));
 const amounts=()=>{const subtotal=products.reduce((sum,p)=>sum+p.price*(bag.items[p.id]||0),0);const shipping=!count()?0:bag.delivery==='tracked'?7:subtotal>=50?0:4.5;return{subtotal,shipping,total:subtotal+shipping};};
 const totals=()=>{const a=amounts();document.querySelector('#subtotal').textContent=money(a.subtotal);document.querySelector('#delivery-total').textContent=money(a.shipping);document.querySelector('#total').textContent=valid()?money(a.total):'Check quantities';save();};
 const render=()=>{rows.innerHTML=products.filter(p=>bag.items[p.id]).map(p=>`<article class="bag-row"><img src="assets/${p.image}.webp" alt="${p.name} pack" width="85" height="85"><div><h2><a href="${p.id}.html">${p.name}</a></h2><p>${p.size} · ${money(p.price)} each</p><label>${p.name} quantity<input type="number" min="1" max="6" step="1" required value="${bag.items[p.id]}" data-quantity="${p.id}"></label><button class="remove" type="button" data-remove="${p.id}">Remove ${p.name}</button></div><strong data-line="${p.id}">${money(p.price*bag.items[p.id])}</strong></article>`).join('')||'<p class="empty-bag">Your bag is empty. <a href="products.html">Explore the collection</a>.</p>';totals();};
 render();
 rows.addEventListener('input',event=>{const input=event.target;if(!input.matches('[data-quantity]'))return;invalidate();if(input.validity.valid&&Number.isInteger(Number(input.value))){bag.items[input.dataset.quantity]=Number(input.value);const p=products.find(p=>p.id===input.dataset.quantity);rows.querySelector(`[data-line="${p.id}"]`).textContent=money(p.price*bag.items[p.id]);}else error.textContent='Use a whole quantity from 1 to 6, or remove the product.';totals();});
 rows.addEventListener('click',event=>{const remove=event.target.closest('[data-remove]');if(!remove)return;delete bag.items[remove.dataset.remove];invalidate();render();document.querySelector('#bag-status').textContent='Product removed. The totals have been updated.';});
 for(const preset of document.querySelectorAll('[data-preset]'))preset.addEventListener('click',()=>{bag.items={};for(const p of products)if(preset.dataset.preset==='all'||p.area===preset.dataset.preset)bag.items[p.id]=1;invalidate();render();document.querySelector('#bag-status').textContent='Bag replaced with your selected starting point.';});
 delivery.addEventListener('change',()=>{bag.delivery=delivery.value;invalidate();totals();});
 document.querySelector('#clear-bag').addEventListener('click',()=>{bag.items={};invalidate();render();document.querySelector('#bag-status').textContent='Your demo bag is clear.';});
 document.querySelector('#create-receipt').addEventListener('click',()=>{invalidate();if(!count()){error.textContent='Add at least one product before creating a receipt.';return;}if(!valid()){error.textContent='Use whole quantities from 1 to 6 before creating a receipt.';rows.querySelector('input:invalid')?.reportValidity();return;}const a=amounts();receiptText=['STILLFERN SKIN / DEMO RECEIPT','Fictional products. No order, payment or shipment.',...products.filter(p=>bag.items[p.id]).map(p=>`${bag.items[p.id]} x ${p.name}, ${p.size}: ${money(p.price*bag.items[p.id])}`),`Products: ${money(a.subtotal)}`,`${bag.delivery==='tracked'?'Tracked':'Standard'} delivery demonstration: ${money(a.shipping)}`,`Illustrative total: ${money(a.total)}`,'GBP catalogue prices. Not a tax invoice.','Prepared in this browser. No personal details collected or transmitted.'].join('\n');document.querySelector('#receipt-lines').textContent=receiptText;receipt.hidden=false;receipt.focus();});
 document.querySelector('#download-receipt').addEventListener('click',()=>{if(!receiptText||receipt.hidden)return;const url=URL.createObjectURL(new Blob([receiptText],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='stillfern-demo-receipt.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}
